{409}{516}Sincro por ShooCat
{2959}{3034}Todos me preguntan|si conozco a Tyler Durden.
{3053}{3082}Tres minutos.
{3084}{3139}Se acabó. Nivel cero.
{3142}{3230}¿Tienes un discurso para la ocasión?
{3233}{3317}Con el caño de un arma en la boca|se habla sólo en vocales.
{3319}{3369}No se me ocurre nada.
{3372}{3463}Por un instante me olvido|de la demolición controlada de Tyler
{3465}{3518}y me pregunto si el arma está limpia.
{3520}{3568}Ahora se pone emocionante.
{3571}{3647}Esa vieja frase:|siempre se hace daño al que se ama.
{3650}{3700}Bueno, funciona para los dos igual.
{3703}{3806}Tenemos la mejor ubicación|para verla destrucción total.
{3808}{3873}El Comité de Demolición|del Proyecto Caos,
{3875}{3957}envolvió los cimientos|de 12 edificios con explosivos.
{3976}{4057}En dos minutos,|la carga volará los cimientos
{4060}{4139}y varios edificios quedarán|reducidos a cenizas.
{4141}{4216}Lo sé porque Tyler lo sabe.
{4216}{4297}Dos minutos y medio.|Piensa en todo lo que logramos.
{4300}{4429}De repente me doy cuenta de que todo,|el arma, las bombas, la revolución
{4431}{4508}tienen algo que ver|con una chica: Marla Singer.
{4520}{4568}HOLA, SOY BOB
{4571}{4628}Bob. Bob tenía una tetas brutales.
{4628}{4729}Era un grupo de apoyo para hombres|con cáncer de testículos.
{4731}{4810}Un gran oso llorándome encima,|ese era Bob.
{4813}{4863}Aún somos hombres.
{4865}{4918}Sí, somos hombres.
{4921}{4973}Hombres es lo que somos.
{4976}{5057}Le quitaron los testículos.|Y luego terapia de hormonas.
{5060}{5151}Le salieron unas tetas enormes|porque le aumentó la testosterona
{5153}{5204}y aumentó su nivel de estrógeno.
{5206}{5295}- Allí es donde yo entro...|- Me drenarán los pectorales de nuevo.
{5297}{5357}..entre esas dos tetas sudorosas
{5359}{5460}que cuelgan enormes|así como Dios es grande.
{5462}{5515}Bueno, llora.
{5518}{5578}No, esperen. Vuelta atrás.|Empiezo otra vez.
{5609}{5673}Hacía seis meses que no podía dormir.
{5676}{5738}No podía dormir...
{5738}{5791}Con el insomnio nada es real.
{5793}{5844}Todo está lejos.
{5865}{5920}Todo es copia de una copia
{5923}{5973}de una copia.
{6028}{6160}Cuando aumente la exploración espacial,|todo tendrá nombre de corporación.
{6165}{6213}La Esfera Estelar IBM.
{6222}{6270}La Galaxia Microsoft.
{6273}{6323}El Planeta Starbucks.
{6338}{6410}Necesito que se ocupe|de algunos problemas.
{6412}{6498}Era Martes.|Llevaba su corbata celeste.
{6501}{6611}¿Quiere que quite prioridad a mis informes|hasta nuevo aviso?
{6611}{6721}Aquí están sus cupones de viaje.|Llámeme si tiene un problema.
{6724}{6817}Estaba lleno de energía. Se debe haber|echo su enema de café con leche.
{6843}{6966}Como tantos, me había vuelto esclavo|del instinto de anidar de Ikea.
{6971}{7026}Quisiera ordenar las fundas
{7028}{7083}contra el polvo de Erika Pekkari.
{7086}{7136}- No corte.|- Las cosas originales
{7138}{7241}como una mesa en forma de yin-yang,|debía poseerlas.
{7268}{7325}Los muebles de oficina de Klipsk.
{7325}{7381}La bicicleta Hovetrekke.
{7390}{7474}O el sofá Ohamshab|con el diseño Strinne verde a rayas.
{7476}{7608}Hasta la pantallas Ryslampa de papel|ecológico sin blanquear.
{7611}{7678}Hojeaba los catálogos y me preguntaba
{7680}{7752}"¿Qué tipo de juego de mesa|me define como persona?"
{7755}{7870}Lo tenía todo. Hasta los platos|de vidrio con burbujas e imperfecciones,
{7872}{7994}prueba de que eran hechos a mano por|el laborioso pueblo indígena de...
{7997}{8066}- No corte.|- ..donde sea.
{8078}{8129}Antes leíamos pornografía.
{8131}{8201}Ahora era la colección Horchow.
{8201}{8282}- No. No se muere de insomnio.|- ¿Y de narcolepsia?
{8284}{8342}Me duermo y despierto|en un sitio extraño.
{8344}{8392}No tengo idea de como llegué allí.
{8395}{8486}- Necesita relajarse.|- ¿Me puede dar algo por favor?
{8488}{8575}Tuinal azul y rojo, Seconal rojo labial.
{8587}{8668}No. Necesita sueño natural.
{8685}{8769}Mastique raíz de valeriana|y haga más ejercicio.
{8819}{8867}Oiga, por favor.
{8869}{8920}- Sufro.|- ¿Quiere ver sufrir?
{8922}{8982}Vaya a First Methodist, martes de noche.
{8985}{9059}Vaya a ver a los que tienen|cáncer de testículos.
{9061}{9112}Eso es sufrir.
{9493}{9574}Siempre quise tres hijos...|dos varones y una niña.
{9577}{9634}Mindy quería dos niñas y un varón.
{9673}{9730}Nunca estábamos de acuerdo en nada.
{9740}{9783}Bueno, yo... Ella...
{9783}{9845}Tuvo su primer hijo la semana pasada.
{9845}{9900}Una niña.
{9903}{9980}Con... Con su... Con su nuevo esposo.
{9999}{10049}¡Coño!
{10083}{10131}Gracias a Dios, saben...
{10133}{10183}Me alegro por ella.
{10203}{10274}Se merece...
{10366}{10457}Todos agradezcamos a Tomás|por compartirlo con nosotros.
{10459}{10509}Gracias, Tomás.
{10512}{10593}Miro a mi alrededor|y veo mucha valentía.
{10596}{10646}Y eso me da fuerzas.
{10649}{10704}Nos damos fuerza los unos a los otros.
{10706}{10761}Ahora la sesión de a dos.
{10776}{10881}Sigamos el ejemplo de Tomás|y abrámonos de verdad.
{10883}{10931}¿Pueden dividirse en pares?
{10984}{11061}Y así conocí al gran oso.
{11102}{11178}Con sus ojos ya encogidos de lágrimas.
{11238}{11305}Rodillas juntas. Esos pasitos extraños.
{11430}{11480}- Me llamo Bob.|- ¿Bob?
{11497}{11550}Bob había sido campeón de culturismo.
{11552}{11641}¿Vieron ese programa de TV sobre|como ensanchar el pecho?
{11644}{11694}Eso era lo suyo.
{11696}{11744}Era un consumidor...
{11747}{11797}Usaba esteroides
{11799}{11859}Diabonal y...
{11862}{11919}Wisterol.
{11919}{12015}Se lo dan a los caballos de carrera,|por Dios.
{12027}{12077}Y ahora estoy quebrado.
{12097}{12147}Divorciado.
{12164}{12217}Mis dos muchachos...
{12236}{12300}ni vienen al teléfono cuando llamo.
{12303}{12423}Desconocidos así de sinceros|me emocionan hasta las lágrimas.
{12468}{12516}Adelante... Cornelius.
{12519}{12569}Puedes llorar.
{12945}{13029}Y entonces... algo sucedió.|Me solté.
{13032}{13082}Eso es muy bueno.
{13082}{13132}Me abandoné.
{13135}{13190}Oscuro, silencioso y total.
{13262}{13351}Encontré la libertad.|Perder la esperanza es liberarse.
{13411}{13461}Está bien.
{13514}{13566}Los bebés no duermen tan bien.
{13653}{13715}Me volví adicto.
{13717}{13785}ALCOHÓLICOS ANÓNIMOS|POSITIVIDAD POSITIVA
{13955}{14008}TUBERCULOSIS|CÓMO COMBATIRLA
{14046}{14094}Si no decía nada
{14096}{14161}la gente suponía lo peor.
{14166}{14214}LIBRE Y CLARO
{14252}{14326}Lloraban más... entonces yo también.
{14365}{14420}CÁNCER DE PIEL, DE RIÑONES, GÁSTRICO
{14552}{14653}Ahora abriremos la puerta verde,|el chakra del corazón...
{14655}{14703}No me estaba muriendo en realidad.
{14708}{14772}No albergaba cáncer ni parásitos.
{14794}{14888}Era el centro tibio en torno al cual|la vida se amontona.
{14911}{14983}Piensen que su dolor|es una esfera de luz que cura.
{14986}{15084}Circula por el cuerpo curándolo.
{15087}{15170}Sigan así. Acuérdense de respirar
{15173}{15262}y den un paso adelante|por la puerta trasera del salón.
{15281}{15331}¿Adónde les lleva?
{15333}{15386}A la caverna.
{15386}{15432}Un paso adelante
{15434}{15487}dentro de la caverna.
{15489}{15540}Así.
{15540}{15624}Entran en lo profundo de la caverna.
{15640}{15691}Y encontrarán allí
{15693}{15743}al animal que les da la fuerza.
{15794}{15827}Resbala.
{16091}{16141}Todas las noches moría.
{16170}{16235}Y cada noche volvía a nacer.
{16249}{16297}Resucitado.
{16345}{16448}Bob me amaba porque creía que también|me habían cortado los testículos.
{16451}{16518}Estando allí, apretado contra sus tetas,
{16520}{16568}dispuesto a llorar.
{16571}{16635}Eran mis vacaciones.
{16691}{16729}Y ella...
{16731}{16796}lo arruinó todo.
{16796}{16849}¿Cáncer es aquí, verdad?
{16916}{16971}Esta chica, Marla Singer,
{16973}{17036}no tenía cáncer de testículos.
{17038}{17089}Era una mentirosa.
{17091}{17141}No tenía ninguna enfermedad.
{17141}{17232}La había visto en Libre y Claro,|mi grupo de parásitos del jueves.
{17235}{17319}Y luego en Esperanza,|mi grupo bimensual de anémicos.
{17331}{17448}Y también en Aprovecha el Día,|mi tuberculosis de los viernes.
{17477}{17525}Marla,
{17527}{17585}la gran turista.
{17587}{17638}Su mentira reflejaba mía.
{17652}{17700}Y de repente, no sentí nada.
{17702}{17791}No podía llorar. De nuevo
{17791}{17841}no podía dormir.
{18105}{18165}El próximo grupo, después de meditar,
{18167}{18249}de abrir el chakra del corazón|cuando hay que abrazarse,
{18251}{18328}voy a agarrara esa perra|Marla Singer, y gritar...
{18328}{18424}¡Marla mentirosa!|¡Turista, yo necesito esto! ¡Vete!
{18474}{18532}Hacía cuatro días que no dormía.
{18534}{18580}Dejaremos secar esto...
{18582}{18664}Cuando se sufre de insomnio,|no se duerme nunca.
{18666}{18726}Y no se está nunca despierto.
{18752}{18812}Para empezar la reunión de esta noche,
{18815}{18880}Chloe querría decir unas palabras.
{18884}{18954}Oh, sí. Chloe.
{18975}{19093}Chloe parecía el esqueleto de|Meryl Streep obligado a circular
{19095}{19146}y ser encantador con todos.
{19158}{19208}Bueno, aún estoy aquí.
{19215}{19268}Pero no sé por cuanto tiempo.
{19287}{19361}Es toda la certeza|que me pueden dar.
{19364}{19412}Tengo buenas noticias también.
{19414}{19503}Ya no temo a la muerte.
{19596}{19688}Pero... me siento muy sola.
{19712}{19762}Nadie quiere hacer el amor conmigo.
{19791}{19896}Estoy tan cerca del fin|y quiero encamarme por última vez.
{19911}{19994}Tengo vídeos pornográficos|en mi apartamento,
{19994}{20083}- y lubricantes y afrodisíacos.|- Gracias, Chloe.
{20100}{20153}Todos, agradezcamos a Chloe.
{20153}{20205}Gracias, Chloe.
{20273}{20364}Ahora preparémonos para|la meditación guiada.
{20392}{20474}Están en la puerta de su caverna.
{20486}{20567}Entran en la caverna y caminan...
{20570}{20647}Si tuviera un tumor lo llamaría Marla.
{20671}{20719}Marla.
{20721}{20826}La raspadura en el paladar|que sanaría sino le pasaras la lengua.
{20829}{20879}Pero no puedes dejar de hacerlo.
{20901}{20970}..dentro de la caverna caminando.
{20973}{21057}Sienten una energía regeneradora.
{21121}{21169}Encuentren al animal de su fuerza.
{21241}{21289}Resbala.
{21373}{21455}Bueno, en pares ahora.
{21457}{21512}Elijan a alguien especial hoy.
{21661}{21711}Oye.
{21721}{21771}- Tenemos que hablar.|- Seguro.
{21886}{21937}- Sé tu secreto.|- ¿Qué?
{21937}{22013}Estás fingiendo. No te estás muriendo.
{22013}{22056}¿Qué?
{22059}{22179}Según la filosofía tibetana, y Sylvia|Plath, sé que todos nos estamos muriendo.
{22181}{22282}- Pero no te estás muriendo como Chloe.|- ¿Y?
{22296}{22347}Eres una turista.
{22349}{22450}Te he visto en melanoma,|en tuberculosis.
{22452}{22512}¡Te vi en cáncer de testículos!
{22514}{22553}Yo te vi practicando.
{22555}{22613}- ¿Practicando qué?|- Regañarme.
{22615}{22706}¿Te sale como esperabas... Rupert?
{22709}{22752}Te denunciaré.
{22754}{22804}Y yo a ti.
{22821}{22891}Únanse. Suelten el llanto.
{23059}{23109}Dios mío. ¿Porqué lo haces?
{23111}{23178}Cuesta menos que el cine|y dan café gratis.
{23181}{23246}Mira, es importante.|Estos son mis grupos.
{23248}{23298}Hace más de un año que vengo.
{23301}{23377}- ¿Y porqué lo haces?|- No sé.
{23380}{23473}Cuando piensan que estás muriendo|te escuchan en lugar de...
{23473}{23545}esperar su turno para hablar.
{23576}{23627}Sí. Sí.
{23656}{23725}Compártanse... completamente.
{23744}{23792}Mira, tú no quieres entrar en esto.
{23795}{23845}- Te vuelves adicto.|- ¿De veras?
{23847}{23951}No bromeo. No puedo llorar si hay otro|impostor presente y lo necesito.
{23953}{24001}Tienes que encontrarte otro sitio.
{24003}{24090}Ve al hospital de cáncer.|No es mi problema.
{24164}{24214}No, espera un momento.
{24217}{24267}Dividimos la semana. ¿Qué piensas?
{24269}{24322}Tú tomas linfoma y tuberculosis.
{24322}{24399}Tú toma tuberculosis.|No aguantan que fume.
{24399}{24480}Bien. Bueno.|Cáncer de testículos no está en duda.
{24483}{24576}Técnicamente yo tengo más derecho.|Tú todavía tienes tus huevos.
{24579}{24634}- Bromeas.|- No sé. ¿Te parece?
{24651}{24684}No. No.
{24687}{24751}- ¿Qué quieres?|- Quiero los parásitos.
{24751}{24818}No puedes tener los dos.|Toma los de sangre.
{24821}{24924}- Quiero los de cerebro.|- Pero quiero la demencia cerebral.
{24926}{24993}- Yo también.|- No puedes tener todo el cerebro.
{24996}{25056}Tú tienes cuatro y yo sólo dos.
{25058}{25152}Te doy los dos parásitos. Son tuyos.
{25154}{25207}Ahora ambos tenemos tres...
{25274}{25336}¡Oye! Dejaste la mitad de tu ropa.
{25734}{25785}- ¿La vendes?|- ¡Sí!
{25787}{25837}¡Vendo algunas ropas!
{25840}{25888}Cada uno tiene tres. Son seis.
{25890}{25960}¿Y el séptimo día?|Quiero cáncer del intestino.
{25960}{26010}La chica había hecho los deberes.
{26012}{26063}Yo quiero cáncer de intestino.
{26080}{26128}¿También es tu favorito?
{26132}{26214}- Trataste de hacerme trampa. ¿No?|- Mira, lo dividimos.
{26219}{26267}Toma el primer y el tercer domingo.
{26327}{26372}Hecho.
{26434}{26490}Bueno entonces nos despedimos.
{26492}{26542}No te pongas sentimental.
{26545}{26602}¿Qué te parece esto entonces?
{26686}{26729}¡Oye, Marla!
{26737}{26789}¡Marla!
{26792}{26854}Deberíamos darnos los teléfonos.
{26856}{26902}¿Te parece?
{26904}{27000}- Podríamos querer cambiar de turno.|- Bien.
{27125}{27185}Así fue como conocía Marla Singer.
{27228}{27329}La filosofía de vida de Marla|era que podía morir en cualquier momento.
{27331}{27386}La tragedia era, decía, que no sucedía.
{27389}{27485}¡No tiene tu nombre!|¿Quién eres? ¿Cornelius? ¿Rupert?
{27487}{27583}¿Travis? ¿Alguno de los nombres|que te cambias cada noche?
{27655}{27703}Despiertas en Sea Tac.
{27705}{27777}SFO. LAX.
{27780}{27835}Despiertas en O'Hare.
{27837}{27890}Dallas Fort Worth.
{27890}{27938}BWI.
{27940}{28031}Pacífico. Central. Pierdes una hora.|Ganas una hora.
{28034}{28125}El chequeo para ese vuelo|es dentro de dos horas, señor.
{28127}{28206}Esta es tu vida,|y se acaba a cada minuto.
{28209}{28281}Despiertas en Air Harbor Internacional.
{28314}{28405}¿Si despiertas a una hora diferente,|en un lugar diferente,
{28408}{28472}podrías despertar como otra persona?
{28475}{28523}Adonde quiera que yo viaje,
{28528}{28580}la vida es diminuta.
{28583}{28643}Azúcar y crema en porción individual.
{28645}{28688}Manteca individual.
{28691}{28758}El paquete Cordon Bleu para microondas.
{28760}{28808}Champú-Condicionador en uno.
{28810}{28902}Paquete muestra de enjuague bucal.|Jaboncitos individuales.
{28938}{28998}La gente que encuentro en cada vuelo...
{29000}{29050}son amigos para un sólo uso.
{29053}{29141}Entre despegue y aterrizaje,|estamos juntos.
{29144}{29197}Es todo el tiempo que tenemos.
{29199}{29244}¡Bienvenido!
{29295}{29396}En una línea de tiempo muy larga|el promedio de supervivencia cae a cero.
{29398}{29487}Era coordinador de retiradas.|Mi trabajo era aplicarla fórmula.
{29489}{29547}El niño atravesó el parabrisas.
{29549}{29647}Un coche nuevo construido por mi compañía|sale a 90 Km. por hora.
{29647}{29698}Se le traba el diferencial trasero.
{29724}{29786}La ortodoncia del chico|pegada al cenicero.
{29786}{29844}Sería un buen aviso contra el tabaco.
{29846}{29930}El coche choca y se incendia|con todos atrapados adentro.
{29933}{29988}¿Lo recuperamos o no?
{29988}{30038}El padre debe haber sido inmenso.
{30040}{30117}¿Ves la grasa que quemó el asiento?|¿La camisa de poliéster?
{30122}{30168}Arte muy moderno.
{30170}{30230}Toma la cantidad de coches: A
{30232}{30297}Multiplica por probabilidad de falla: B
{30299}{30391}Multiplica por el promedio|de arreglos extrajudiciales, C.
{30393}{30443}A x B x C
{30448}{30494}igual a X.
{30496}{30558}Si X es menos del costo|para recuperarlo,
{30558}{30609}no se efectúa.
{30611}{30688}¿Hay muchos de estos accidentes?
{30688}{30736}No lo creería.
{30769}{30832}¿Para qué compañía trabaja?
{30832}{30884}Una grande.
{30944}{31038}Cada ves que el avión se inclinaba|al despegar o aterrizar,
{31040}{31119}rogaba por un accidente|o un choque en el aire.
{31134}{31172}Cualquier cosa.
{31383}{31474}El seguro de vida paga triple|si mueres en un viaje de negocios.
{31544}{31623}"Si está sentado|en una salida de emergencia
{31625}{31709}y no puede o no desea|realizar las tareas
{31712}{31817}de seguridad pida|que le cambien de asiento."
{31860}{31911}Es mucha responsabilidad.
{31913}{31966}¿Quieres cambiar de asiento?
{31968}{32050}No. No creo.|No soy el hombre para esa tarea.
{32052}{32158}Una salida de emergencia|a 9.000 m de altura.
{32160}{32210}La ilusión de seguridad.
{32215}{32265}Sí. Ya lo creo.
{32268}{32337}¿Sabes por qué hay máscaras de oxígeno|en los aviones?
{32340}{32448}- Para que puedas respirar.|- El oxígeno te coloca.
{32476}{32560}En una catástrofe,|inhalas mucho, por el pánico.
{32563}{32623}Y te pones eufórico y dócil.
{32625}{32680}Aceptas tu destino.
{32695}{32743}Está todo aquí.
{32745}{32822}Amerizaje de emergencia a 900 kph.
{32824}{32891}Caras sin expresión. Como vacas hindúes.
{32894}{32944}Es...
{32973}{33028}Es una teoría interesante.
{33076}{33126}- ¿Qué haces?|- ¿Qué quieres decir?
{33129}{33179}¿En qué trabajas?
{33179}{33256}¿Porqué?|¿Para fingir que te interesa?
{33320}{33356}Bien.
{33359}{33428}Tu risa tiene|una desesperación enfermiza.
{33505}{33555}Tenemos maletines idénticos.
{33575}{33623}Jabón.
{33625}{33714}- ¿Cómo?|- Fabrico y vendo jabón.
{33716}{33774}La medida de la civilización.
{33786}{33831}Y así fue como conocí a...
{33836}{33879}Tyler Durden.
{33879}{34006}¿Sabías que mezclando gasolina con|jugo de naranja congelado haces napalm?
{34009}{34080}- No, no sabía. ¿Es verdad?|- Es así.
{34083}{34174}Se pueden hacer diversos explosivos|con artículos para el hogar.
{34176}{34234}- ¿De veras?|- Si uno lo desea.
{34354}{34476}Tyler, eres de lejos el mejor amigo|para uso individual.
{34519}{34620}- Todo abordo es de uso individual...|- Oh, ya veo. Muy listo.
{34620}{34658}Gracias.
{34661}{34711}¿Funciona para ti?
{34713}{34778}- ¿Qué|- Ser listo.
{34781}{34838}Mucho.
{34841}{34912}Sigue, entonces. Sigue.
{34941}{34992}Una cuestión de etiqueta.
{34994}{35066}¿Al pasar te doy el culo o la bragueta?
{35236}{35291}Como fui a vivir con Tyler es...
{35294}{35397}Las líneas aéreas tienen una política|para equipajes que vibran.
{35579}{35692}- ¿Estaba latiendo?|- Ellos saben que hoy las bombas no laten.
{35694}{35768}- ¿Quiénes saben?|- Los maleteros.
{35771}{35826}Pero cuando una maleta vibra,
{35828}{35893}los maleteros llaman a la policía.
{35895}{35979}- ¿Mi maleta vibraba?|- Nueve de cada diez veces
{35982}{36030}es una afeitadora eléctrica.
{36032}{36082}Pero cada tanto...
{36154}{36202}Es un vibrador.
{36222}{36320}Es política de la compañía nunca|sugerir la propiedad de un vibrador.
{36322}{36413}Se usa el artículo indefinido,|un vibrador, nunca es
{36416}{36466}su vibrador.
{36468}{36519}Yo no poseo...
{36584}{36658}Tenía todo en esa maleta.|Mis camisas CK.
{36660}{36735}Mis zapatos DKNY. Mis corbatas AX.
{36775}{36831}No importa.
{36876}{36941}¡Qué coche!
{37089}{37140}Vivía en un piso 15
{37142}{37214}de un fichero|para viudas y profesionales.
{37217}{37279}Los muros eran de hormigón sólido.
{37284}{37332}La barrera de hormigón es importante
{37334}{37437}cuando tu vecino tiene que ver|televisión a todo volumen.
{37440}{37533}O cuando una explosión de lo que|fueron tus efectos personales
{37533}{37631}sale de tus ventanas|y vuela en llamas hacia la noche.
{37785}{37840}Supongo que son cosas que suceden.
{38149}{38197}No...quedó nada allí arriba.
{38200}{38281}No puede entrar. Por orden policial.
{38490}{38550}¿Tiene a quién llamar?
{38552}{38602}Qué vergüenza.
{38605}{38674}Una casa llena de condimentos|y sin comida.
{38902}{38991}La policía me dijo después|que tal vez se apagó el piloto
{39015}{39087}dejando escapar el gas.
{39089}{39142}Ese gas podía haber llenado el piso,
{39144}{39228}150 metros cuadrados con techos altos,|durante varios días.
{39425}{39516}Y si el compresor del refrigerador|se había activado...
{39542}{39593}¿Sí?
{39667}{39717}Te oigo respirar...
{39923}{40019}Si me lo preguntan ahora,|no podría decir por qué lo llamé.
{41055}{41108}- ¿Hola?|- ¿Quién es?
{41163}{41213}- ¿Tyler?|- ¿Quién es?
{41249}{41302}Nos conocimos... en el avión.
{41304}{41357}¿Teníamos el mismo maletín?
{41360}{41410}¿El tipo listo?
{41412}{41470}Oh, sí. Claro.
{41518}{41580}Llamé hace un momento. Nadie respondió.
{41583}{41683}- Estoy en un teléfono público.|- Sí, yo nunca respondo el teléfono.
{41748}{41798}¿Qué sucede?
{41815}{41863}Bueno.
{41866}{41916}No me vas a creer.
{41966}{42021}Sabes, podría ser peor.
{42021}{42112}Alguien te corta el pene mientras|duermes y lo tira por la ventana.
{42134}{42213}Sí, podría ser. No lo sé.
{42213}{42290}Cuando compras muebles|te dices: ya está.
{42290}{42340}Es el último sofá que necesitaré.
{42343}{42410}Suceda lo que suceda,|lo del sofá está resuelto.
{42412}{42494}Lo tenía todo.|Tenía un estéreo decente.
{42496}{42582}Un guardarropa respetable.
{42582}{42635}Casi estaba completo.
{42638}{42698}- Mierda. Ahora lo perdiste todo.|- Todo.
{42700}{42767}Todo.
{42796}{42846}¿Sabes qué es un duvet?
{42849}{42918}- Un cobertor.|- Es una manta.
{42918}{43014}Una manta. ¿Porqué tipos como tú|y yo sabemos lo que es un duvet?
{43016}{43117}¿Es esencial a la supervivencia|en el sentido del cazador-agricultor?
{43119}{43158}No.
{43160}{43208}¿Qué somos entonces?
{43211}{43273}No sé. Consumidores.
{43273}{43323}Bien. Somos consumidores.
{43326}{43405}Somos subproductos de una obsesión|por el estilo.
{43407}{43501}Asesinato, crimen, pobreza.|Esas cosas no me preocupan.
{43503}{43585}Lo que me preocupa|son las revistas de personajes famosos
{43587}{43637}500 canales de televisión,
{43637}{43702}un nombre en la ropa interior. Rogaine.
{43705}{43755}Viagra. Olestra.
{43757}{43824}- Martha Stewart.|- A la mierda con Martha Stewart.
{43827}{43911}Está lustrando los bronces del Titanic.|Todo se hunde.
{43913}{44002}Vete a la mierda con tus sofás|Strinne a rayas verdes.
{44004}{44083}Te digo: No estés completo nunca.
{44086}{44134}Te digo: Deja de ser perfecto.
{44136}{44186}Te digo: hay que evolucionar.
{44186}{44242}Que las fichas caigan donde caigan.
{44294}{44345}Así soy yo, quizás esté equivocado.
{44347}{44397}Quizás sea una tragedia terrible.
{44397}{44457}Son cosas. No es una tragedia...
{44460}{44551}Has perdido soluciones versátiles|para la vida moderna.
{44553}{44613}Mierda, tienes razón. No fumo.
{44695}{44786}Mi seguro va a cubrirlo, de modo que...
{44843}{44896}¿Qué?
{44899}{44973}Tus posesiones terminan por poseerte.
{45052}{45102}Haz lo que quieras, hombre.
{45119}{45179}Oh, es tarde.
{45179}{45246}- Oye, gracias por la cerveza.|- Sí, hombre.
{45249}{45297}Debería buscar hotel.
{45316}{45366}- ¡Oh!|- ¿Qué?
{45368}{45407}¿Qué?
{45409}{45457}- ¿Un hotel?|- Sí.
{45462}{45534}- Pide, hombre.|- ¿De qué estás hablando?
{45536}{45627}Con tres jarras de cerveza|y aún no puedes pedir.
{45651}{45690}¿Qué?
{45692}{45754}Me llamaste|porque necesitabas adónde quedarte.
{45757}{45841}- Oye. No, no, no.|- Sí, fue así. Pídemelo.
{45841}{45903}Déjate de vueltas y pídemelo, hombre.
{45946}{46001}¿Sería un problema?
{46004}{46052}¿Es un problema para ti pedir?
{46078}{46131}- ¿Puedo dormir en tu casa?|- Sí.
{46164}{46212}Gracias.
{46313}{46385}- Quiero que me hagas un favor.|- Sí, claro.
{46387}{46445}Quiero que me pegues muy fuerte.
{46447}{46493}¿Qué?
{46495}{46586}Quiero que me pegues bien fuerte.
{46589}{46658}Déjenme hablarles de Tyler Durden.
{46663}{46721}Tyler era una persona nocturna.
{46723}{46776}Los demás dormíamos mientras él trabajaba.
{46778}{46855}Trabajaba de proyeccionista.
{46857}{46927}Las películas no vienen en un rollo.|Sino en varios.
{46932}{47020}Alguien tiene que cambiar de proyector|en el preciso momento
{47023}{47100}en que termina un rollo y empieza otro.
{47102}{47195}Se ven unos puntitos|a la derecha en pantalla.
{47198}{47263}Les llaman quemaduras de cigarrillo.
{47265}{47315}Son la clave para el cambio.
{47315}{47430}Se cambia el proyector, la película|sigue y el público ni se entera.
{47433}{47486}¿Porqué hacer este trabajo de mierda?
{47488}{47565}Porque brinda oportunidades interesantes.
{47567}{47651}Como meter un segundo de pornografía|en películas para niños.
{47653}{47773}Cuando los animales con voces famosas|se encuentran por primera vez
{47776}{47876}saldrá el flash con la contribución|de Tyler a la película.
{48042}{48104}Nadie sabe que lo vio pero lo vieron.
{48107}{48169}Un buen pene bien gordo.
{48284}{48349}Nadie podría pillar a Tyler.
{48478}{48598}Tyler también trabajaba a veces|de camarero en el Hotel Pressman.
{48708}{48807}Era el terrorista|de la industria alimenticia.
{48809}{48864}No mires. No puedo orinar si miran.
{48867}{48972}Además de sazonar la sopa de langosta,|se tiraba pedos en los merengues,
{48972}{49034}y en cuanto a la crema de hongos...
{49037}{49085}Vamos, diles.
{49087}{49135}Ustedes se dan una idea.
{49140}{49217}- ¿Quieres que te pegue?|- Vamos. Hazme el favor.
{49219}{49301}- ¿Porqué?|- Nunca estuve en una pelea. ¿Y tú?
{49303}{49399}- No. Pero eso es bueno.|- ¡No te conoces si no has peleado!
{49401}{49456}No quiero morir sin cicatrices.
{49459}{49562}- Pégame, antes de que me acobarde.|- Dios. Esto es una locura.
{49564}{49619}¡Ponte loco! Entrégate.
{49619}{49684}- No sé si es buena idea.|- Yo tampoco.
{49687}{49761}¿Y qué importa? Nadie mira.|¿Qué te importa?
{49763}{49821}Es una locura. ¿Quieres que te pegue?
{49823}{49874}Sí.
{49876}{49953}- ¿Dónde? ¿En la cara?|- Sorpréndeme.
{50003}{50053}Esto es una gran estupidez.
{50315}{50368}¡Cabrón!
{50370}{50420}¡Me pegó en la oreja!
{50423}{50499}- Bueno, lo siento.|- ¡Cristo!
{50502}{50550}- ¿Porqué en la oreja?|- Lo cagué.
{50552}{50593}No, fue perfecto.
{50902}{50953}No, está bien.
{50974}{51024}Duele de verdad.
{51034}{51084}Bien.
{51094}{51147}Pégame otra vez.
{51147}{51199}No, pégame tú a mí. ¡Vamos!
{51605}{51665}Deberíamos volver a hacerlo alguna vez.
{51859}{51909}CALLE PAPER
{51972}{52024}- ¿Dónde está tu coche?|- ¿Qué coche?
{52276}{52334}No sé como Tyler encontró esa casa,
{52336}{52389}dijo que hacía un año que la tenía.
{52391}{52461}Parecía esperarla demolición.
{52463}{52521}Casi todas las ventanas estaban tapiadas.
{52523}{52652}No había cerradura en la puerta pues|la policía la había roto a patadas.
{52652}{52703}La escalera se derrumbaba.
{52705}{52765}No sé si la casa era suya o si era un intruso.
{52768}{52827}Nada me hubiera sorprendido.
{52849}{52899}Sí. Allí estás tu.
{52902}{52964}Allí yo. Ese es el baño. ¿Bien?
{52964}{53014}Sí, gracias.
{53017}{53062}Qué cloaca.
{53065}{53113}Nada funcionaba.
{53199}{53293}Al encender una luz se apagaba otra.
{53297}{53386}No había vecinos.|Sólo depósitos y una fábrica de papel.
{53389}{53482}El olor inmundo del vapor.|El olor a jaula sucia de las astillas.
{53525}{53583}¿Qué es esto?
{53938}{53988}- Hola, muchachos.|- Hola.
{54252}{54326}Cuando llovía se cortaba la luz.
{54348}{54429}Al terminar el primer mes|ya no extrañaba la TV.
{54453}{54532}Ni me disgustaba|el refrigerador tibio.
{54829}{54880}¿Puedo ser el próximo?
{54985}{55036}Bueno, hombre.
{55038}{55086}Afloja la corbata.
{55182}{55287}De noche, Tyler y yo éramos|los únicos en el barrio.
{55417}{55513}La lluvia entraba por las grietas.
{55513}{55582}La madera se hinchaba y encogía.
{55585}{55661}Había clavos herrumbrados|para arañarse los codos.
{55664}{55724}El anterior ocupante era un solitario.
{55726}{55777}Oye, hombre. ¿Qué lees?
{55779}{55884}Escucha. Es un artículo escrito|por un órgano en primera persona.
{55884}{55952}"Soy el bulbo raquídeo de Jack.|Sin mí,
{55954}{56038}Jack no podría controlar|su corazón ni respirar."
{56038}{56088}Hay toda una serie.
{56091}{56141}"Soy los pezones de Jill."
{56189}{56285}- "Soy el colon de Jack."|- "Me viene cáncer. Mato a Jack."
{56362}{56453}Después de pelear,|todo en la vida tenía menos volumen.
{56517}{56541}¿Qué?
{56546}{56630}- Se podía hacer frente a todo.|- ¿Ha terminado los informes?
{56743}{56805}¿Si pudieras elegir, con quién pelearías?
{56805}{56855}Con mi jefe, probablemente.
{56858}{56908}¿De veras?
{56911}{56992}- Sí, ¿Porqué? ¿Con quién pelearías tu?|- Con mi padre.
{56992}{57042}Yo no conozco a mi padre.
{57045}{57090}Bueno, lo conozco pero...
{57093}{57150}Se fue cuando yo tenía seis años.
{57150}{57222}Se casó con otra mujer y tuvo otros hijos.
{57225}{57275}Lo hacía cada seis años.
{57280}{57376}- Cambiaba de ciudad y de familia.|- Tenía un sistema de licencias.
{57397}{57448}Mi padre no fue a la universidad.
{57450}{57544}- Era muy importante que yo fuera.|- Eso lo he oído antes.
{57546}{57651}Me gradúo. Lo llamo larga distancia|y le digo: "Y ahora, qué?"
{57654}{57702}- "Consigue empleo."|- A mi igual.
{57704}{57769}A los 25 años hago el llamado anual.
{57769}{57817}"Y ahora qué, Papá?"
{57819}{57870}Dice: "No sé. Cásate."
{57872}{57956}Yo no me puedo casar.
{57975}{58023}Soy un niño de 30 años.
{58026}{58085}Somos una generación criada por mujeres.
{58088}{58191}Me pregunto si otra mujer|es lo que necesitamos.
{58335}{58412}Durante la semana éramos perfectos.
{58433}{58515}Pero los sábados por la noche|descubríamos algo.
{58543}{58627}Descubríamos cada vez más|que no estábamos solos.
{58721}{58831}Antes cuando llegaba a casa irritado|o deprimido limpiaba el apartamento.
{58834}{58884}Lustraba mis muebles suecos.
{58889}{59009}Debería estar buscando un apartamento|o discutiendo con la compañía de seguros.
{59011}{59100}Debería sentirme enfadado|por mis posesiones de mierda.
{59104}{59148}Pero no.
{59152}{59239}Se cibernetiza una oficina|para que sea más eficiente.
{59241}{59308}El lunes pensaba en la semana siguiente.
{59311}{59383}¿El icono puede ser celeste?
{59385}{59411}Desde luego.
{59416}{59493}La eficiencia es la prioridad 1.
{59495}{59562}Porque desperdiciar es robar.
{59565}{59639}Se lo mostré a mi amigo aquí.|¿Te gustó, verdad?
{59728}{59824}Se puede tragar un litro de sangre|antes de vomitar.
{59845}{59900}Era evidente.
{59903}{59956}Tyler y yo lo hicimos visible.
{59958}{60016}Todos lo tenían|en la punta de la lengua.
{60018}{60068}Tyler y yo le pusimos nombre.
{60337}{60385}¡Vamos, hay que irse a casa!
{60919}{60975}Apaga la gramola. Cierra atrás.
{61476}{61564}Todas las semanas,|Tyler leía las reglas que habíamos hecho.
{61567}{61617}¡Señores!
{61634}{61684}Bienvenidos al Club de Lucha.
{61735}{61787}La primera regla del Club es
{61790}{61847}no se habla del Club de Lucha.
{61850}{61912}La segunda regla del Club es
{61922}{62003}¡no se habla del Club!
{62006}{62061}La tercera regla del Club.
{62063}{62130}Si alguien grita "basta",|no puede moverse,
{62133}{62200}la pelea se acabó. Cuarta regla.
{62200}{62257}Dos hombres por pelea.
{62257}{62303}Quinta regla.
{62305}{62344}Una pelea a la vez.
{62372}{62430}Sexta regla. Sin camisa. Ni zapatos.
{62432}{62526}Séptima regla.|Las peleas durarán lo que deban durar.
{62571}{62634}Y octava y última regla.
{62660}{62737}Si es tu primera noche en el Club,
{62739}{62790}tienes que pelear.
{62885}{62936}Este chico de la oficina, Ricky,
{62938}{63046}no podía recordar si habías|pedido tinta azul o negra.
{63049}{63106}Pero esos diez minutos Ricky fue un dios
{63108}{63188}cuando aplastó|al camarero de un local vecino.
{63233}{63360}A veces sólo se oía el sonido|de los puños y los gritos.
{63451}{63523}O el sonido húmedo atragantado|de alguien que rogaba...
{63526}{63574}¡Basta!
{63576}{63646}No se estaba vivo|en ninguna parte como allí.
{63648}{63763}Pero el Club de Lucha sólo existe|durante algunas horas.
{63775}{63847}Aun si pudiera felicitar a alguien|por una buena pelea,
{63852}{63907}no estaría hablando|con la misma persona.
{63909}{63988}El que eras en el Club|no era el mismo que fuera del Club.
{63991}{64111}Un tipo vino al Club por primera vez.|Tenía el culo blando como masa para pan.
{64113}{64180}Semanas más tarde parecía|tallado en madera.
{64202}{64279}¿Si pudieras pelear con|alguien famoso quién sería?
{64279}{64355}- ¿Vivo o muerto?|- Da igual. ¿Quién sería duro?
{64377}{64451}Hemingway. ¿Y tú?
{64468}{64542}William Shatner.
{64569}{64645}Empezamos a ver todo de otra manera.
{64677}{64756}A dondequiera que fuéramos,|nos formábamos una opinión.
{64835}{64911}Me daban pena los tipos en el gimnasio,
{64914}{65012}queriendo serlo que Calvin Klein|o Tommy Hilfiger les indicaran.
{65012}{65065}¿Eso es un hombre?
{65087}{65154}Mejorarse el físico es masturbarse.
{65156}{65206}La autodestrucción...
{65209}{65257}Perdón.
{66086}{66163}El Club de Lucha no era|cosa de ganar o perder.
{66165}{66213}No era cosa de palabras.
{66261}{66345}Los gritos eran otro idioma...
{66348}{66393}..como en un rito religioso.
{66503}{66554}- ¿Eso es todo?|- ¡Basta!
{66554}{66623}La pelea acababa sin resolver nada.
{66626}{66671}Pero nada importaba.
{66674}{66741}Muy bien.
{66743}{66810}Después, todos nos sentíamos a salvo.
{66832}{66887}Oye. ¿Qué tal la semana próxima?
{66890}{66937}¿Qué tal el mes próximo?
{66942}{66990}Todos aquí en el medio.
{66993}{67041}Tú, el nuevo, también.
{67084}{67136}A veces, Tyler hablaba por mí.
{67139}{67189}Se cayó por la escalera.
{67204}{67254}Me caí por la escalera.
{67297}{67410}El Club fue el motivo para cortarse|el pelo y las uñas al ras.
{67412}{67472}Cualquier figura histórica.
{67475}{67518}Pelearía con Gandhi.
{67534}{67578}Buena respuesta.
{67580}{67633}- ¿Y tú?|- Lincoln.
{67635}{67698}¿Lincoln?
{67700}{67786}Tipo alto y grande.|Los delgados pelean hasta que los acaben.
{67808}{67858}¡Mierda!
{67887}{67952}Hasta la Mona Lisa se cae a pedazos.
{68167}{68201}¿Hola?
{68203}{68261}¿Dónde has estado estas ocho semanas?
{68263}{68295}¿Marla?
{68366}{68441}- ¿Cómo me encontraste?|- El mensaje en tu teléfono.
{68446}{68515}No te he visto en ningún grupo de apoyo.
{68517}{68594}Los dividimos.|Esa fue la idea. ¿Recuerdas?
{68597}{68666}Pero tú no has ido a los tuyos.
{68666}{68752}- ¿Cómo sabes?|- Hice trampa.
{68752}{68798}Encontré uno nuevo.
{68810}{68865}- ¿Realmente?|- Es sólo para hombres.
{68868}{68906}¿Cómo el de testículos?
{68995}{69045}Mira, es un mal momento.
{69045}{69105}He asistido a Deudores Anónimos.
{69107}{69191}- Son gente con muchos problemas...|- Estoy saliendo.
{69194}{69251}Yo también. Estoy llena de Xanax.
{69254}{69309}Me tomé lo que quedaba en el frasco.
{69311}{69359}Quizás fue demasiado.
{69361}{69450}Imaginen a Marla Singer tirada|en su inmundo apartamento.
{69453}{69560}No era un suicidio de verdad.|Más bien un pedido de auxilio.
{69563}{69632}¿No sales esta noche?
{69635}{69702}¿Quieres esperar|y oírme describir la muerte?
{69704}{69812}¿Quieres escuchar y ver|si mi espíritu usa el teléfono?
{69865}{69930}¿Has oído alguna vez un estertor?
{70560}{70675}La puerta de Tyler estaba cerrada.|Nunca la cerraba.
{70795}{70870}No me vas a creer el sueño|que tuve anoche.
{70872}{70951}No puedo creer nada de anoche.
{71186}{71234}¿Qué haces aquí?
{71299}{71349}¿Qué?
{71349}{71409}Esta es mi casa.|¿Qué haces aquí?
{71467}{71515}¡Vete a la mierda!
{71865}{71946}¡Qué amistades jodidas tienes!
{71948}{71996}Flexible, no obstante.
{71996}{72044}Esa cosa.
{72071}{72136}Llego anoche. El teléfono descolgado.
{72138}{72188}¿Y quién está al otro lado?
{72191}{72243}Sabía la historia antes de oírla.
{72299}{72385}¿Has oído alguna vez un estertor?
{72385}{72454}¿Crees que sea lo que se piensa?
{72457}{72543}¿O tal vez sea una simple arcada?
{72625}{72721}Prepárense a evacuar el alma.
{72723}{72761}Diez,
{72764}{72831}nueve,... ocho,...
{72833}{72886}¿Cómo pudo Tyler,
{72888}{72982}pensar que la muerte de|Marla Singer era algo malo?
{72982}{73023}..cinco,
{73025}{73063}cuatro...
{73080}{73131}Espera.
{73262}{73318}Llegaste rápido...
{73354}{73404}¿Yo te llamé?
{73660}{73735}El colchón está envuelto|en plástico resbaloso.
{73814}{73871}No te preocupes.|No es un peligro para ti.
{73939}{73984}¡Oh, mierda!
{73984}{74034}Alguien llamó a la policía.
{74322}{74406}- ¿Dónde es el 513?|- Final del corredor.
{74425}{74516}La chica que vivía allí|era encantadora.
{74519}{74571}Perdió la fe en sí misma.
{74574}{74641}- ¡Déjenos ayudarla!|- ¡Es un monstruo!
{74643}{74742}- Tiene motivos para vivir.|- ¡Es una basura humana!
{74744}{74835}- ¡Miss Singer!|- ¡Suerte para salvarla!
{74950}{75003}Si me duermo,
{75005}{75061}me muero.
{75106}{75159}Vas a tener que mantenerme despierta
{75161}{75212}toda la noche.
{75214}{75269}Increíble.
{75272}{75324}Era obvio que manejaba la situación.
{75324}{75413}- Sabes lo que digo, tú la follaste.|- No, no lo hice.
{75415}{75466}- ¿Nunca?|- No.
{75487}{75540}¿No te interesa, verdad?
{75540}{75590}¡No! Por Dios, para nada.
{75593}{75655}Soy el conducto biliar de Jack.
{75660}{75706}¿Seguro? A mí me lo puedes decir.
{75708}{75751}Créemelo, estoy seguro.
{75756}{75833}- Vuélame los sesos contra la pared...|- Eso es bueno.
{75835}{75902}Es un ave de presa que finge ser débil.|Aléjate.
{75948}{76036}La mierda que salía de su boca.|¡Jamás oí algo similar!
{76039}{76077}Dios mío.
{76080}{76161}No me habían penetrado así|desde la escuela primaria.
{76164}{76221}¿Cómo Tyler no iba a volverse loco?
{76223}{76310}La otra noche metió sexo|en la proyección de Cenicienta.
{76312}{76379}No necesita un amante,|sino un asistente social.
{76379}{76442}O un baño.|No es amor, es hacerlo por deporte.
{76446}{76514}Invadió mis grupos de apoyo|y ahora mi hogar.
{76516}{76566}Oye. Siéntate.
{76665}{76746}Escucha.|No puedo permitir que le hables de mí.
{76749}{76792}¿Porqué lo haría...?
{76794}{76924}Dile lo que sucede en esta casa|a ella o a otra y se acabó.
{76926}{76988}- Prométemelo. ¿Prometes?|- Sí.
{76991}{77041}- Sí, lo prometo.|- ¿Lo prometes?
{77043}{77125}- Lo he dicho: lo prometo...|- Has prometido tres veces.
{77161}{77257}Si hubiera perdido unos minutos|en ira ver morir a Marla Singer,
{77259}{77310}nada de esto hubiera sucedido.
{77427}{77497}¡Más duro, sí! ¡Oh, más fuerte!
{77655}{77715}Me podría haber cambiado de cuarto.
{77741}{77835}En el tercer piso no los hubiera oído.
{77835}{77885}Pero no lo hice.
{78468}{78566}- ¿Qué haces?|- Me voy a la cama.
{78568}{78616}¿Quieres acabarla?
{78686}{78772}- No. No, gracias.|- Encontré un cigarrillo.
{78775}{78854}- ¿Con quien hablabas?|- Cállate.
{78856}{78935}Me convertí en el centro calmo|del mundo.
{78952}{79000}Era el maestro Zen.
{79045}{79081}LAS ABEJAS PUEDEN IRSE
{79081}{79122}LOS ZÁNGANOS PUEDEN IRSE
{79125}{79173}Escribí poemas haiku.
{79187}{79242}Los envié por correo electrónico.
{79244}{79295}¿Esa sangre es suya?
{79336}{79386}En parte, sí.
{79388}{79451}No se puede fumar aquí.
{79453}{79503}Tómate el día libre.
{79506}{79566}Vuelve el lunes con ropa limpia.
{79568}{79618}Mira lo que haces.
{79628}{79683}Ignoré las miradas hostiles de todos.
{79686}{79746}"Sí, son moretones de peleas."
{79748}{79798}"Sí, me siento cómodo con ello."
{79801}{79846}"Soy un iluminado."
{79892}{80014}Renuncias al apartamento,|a todas tus posesiones materiales,
{80016}{80091}te mudas a una ruina|en un barrio tóxico de la ciudad,
{80093}{80187}para llegara casa a esto.
{80441}{80522}- Hola.|- Soy el Detective Stern de Incendios.
{80525}{80628}Tengo información sobre el incendio|en su apartamento.
{80628}{80659}Sí.
{80661}{80779}Alguien roció la cerradura con Freon.
{80781}{80846}Usaron un cincel|para romper el cilindro.
{80848}{80896}No, no lo sabía.
{80896}{80944}Soy el sudor frío de Jack.
{80947}{81002}¿Le suena extraño?
{81004}{81071}Sí, señor, muy extraño.
{81074}{81122}- La dinamita...|- ¿Dinamita?
{81124}{81199}..dejó huellas de potasio|con oxalato de amoníaco.
{81203}{81285}- ¿Sabe lo que significa?|- No. ¿Qué significa?
{81287}{81333}Que era casera.
{81335}{81438}Lo siento.|Esto es un shock para mí, señor.
{81438}{81573}El que puso la dinamita apagó|el piloto días antes de la explosión.
{81575}{81649}- el gas fue el detonante.|- ¿Y quién haría eso?
{81649}{81700}- Yo hago las preguntas.|- Díselo.
{81702}{81808}Dile: el liberador que destruyó|mi casa realineó mi percepción.
{81810}{81860}Perdón. ¿Sigue allí?
{81863}{81932}Le escucho.|Es difícil saber qué pensar.
{81935}{82042}¿Tiene enemigos que tengan acceso|a la dinamita casera?
{82045}{82098}- ¿Enemigos?|- Rechazo la civilización,
{82100}{82150}y las posesiones materiales.
{82153}{82222}- Hijo, esto es serio.|- Sí, sé que lo es.
{82222}{82285}- Lo digo en serio.|- Sí, muy serio.
{82287}{82357}Mire, nadie se toma esto|más en serio que yo.
{82357}{82424}Ese apartamento era mi vida.
{82426}{82510}Yo amaba los muebles que tenía.
{82512}{82584}No fue un montón de cosas|que destruyeron.
{82587}{82656}- ¡Fue a mí!|- Quiero agradecer a la Academia...
{82659}{82755}- ¿No es buen momento para usted?|- ¡Dile que lo hiciste tú, coño!
{82757}{82850}¡Dile que lo volaste tu mismo!|Eso es lo que quiere oír.
{82853}{82970}- ¿Sigue usted allí?|- Espere. ¿Sospecha de mí?
{82970}{83066}No. Puedo necesitar hablarle.|Si sale de la ciudad me lo dice.
{83069}{83126}- ¿De acuerdo?|- Bien.
{83191}{83301}Excepto cuando lo hacían,|Tyler y Marla nunca estaban juntos.
{83304}{83378}Mis padres fueron así durante años.
{83380}{83469}El condón es como|el zapato de la Cenicienta de hoy.
{83471}{83541}Te lo pones cuando vas con un extraño.
{83543}{83594}Bailas toda la noche.
{83596}{83646}Y luego lo arrojas a la basura.
{83651}{83714}Al condón, claro. No al extraño.
{83752}{83788}¿Qué?
{83903}{83970}Compré este vestido usado por un dólar.
{83973}{84018}Lo vale.
{84021}{84068}Es de dama de honor.
{84092}{84169}Alguien lo amó intensamente
{84172}{84220}por un día.
{84222}{84272}Y luego lo tiró.
{84318}{84366}Como un árbol de navidad.
{84371}{84421}Tan especial.
{84423}{84457}Y luego...
{84505}{84553}lo tiran a la calle.
{84567}{84618}Con el papel plateado colgando.
{84668}{84718}Como víctima de un crimen pasional.
{84718}{84769}Los calzones al revés.
{84785}{84876}- Atada con cinta aislante.|- Te sienta.
{84879}{84944}Te lo presto cuando quieras.
{85111}{85162}Échala.
{85181}{85251}- ¿Qué? ¡Échala tú!|- No me menciones.
{85253}{85354}Vuelvo a tener seis años,|pasando mensajes entre mis padres.
{85402}{85488}- Es hora de que te vayas.|- No te preocupes, me voy.
{85490}{85601}- No es que no nos gusten tus visitas.|- Estás loco. Quién te entiende.
{85653}{85723}Tengo que bajarme
{85725}{85754}Gracias. Adiós.
{85756}{85900}Tengo que bajarme de esta calesita.
{85917}{86011}Tengo que conseguir...
{86013}{86061}Tengo que...
{86114}{86150}¡Qué chicos!
{86198}{86255}¿Porqué pierdes el tiempo con ella?
{86258}{86315}Tengo que admitir de Marla...
{86315}{86370}que al menos trata de tocar fondo.
{86373}{86404}¿Y yo no?
{86406}{86473}No eres pollo porque|te llenes el culo de plumas.
{86476}{86526}¿Qué hacemos esta noche?
{86543}{86596}Esta noche... hacemos jabón.
{86620}{86646}¿De veras?
{86648}{86715}Para hacer jabón,|primero se derrite la grasa.
{87169}{87224}La sal es importante
{87226}{87286}así que la mejor grasa es la humana.
{87305}{87380}- ¿Dónde estamos?|- Una clínica de liposucción.
{87574}{87622}¡Aquí está!
{87624}{87718}La grasa más rica y cremosa.|¡La mejor grasa!
{87852}{87936}¡No! ¡No tires, no tires!
{88046}{88101}- ¡Oh, Dios!|- Dame otra.
{88248}{88331}Cuando se derrite,|la grasa flota en la superficie.
{88334}{88384}Como los Boy Scouts.
{88384}{88475}- Difícil imaginarte como Boy Scout.|- Sigue removiendo.
{88533}{88617}Cuando la grasa se endurece,|retiras la capa de glicerina.
{88619}{88677}Pones ácido nítrico y es nitroglicerina.
{88679}{88773}Agregas nitrato de sodio y aserrín,|y tienes dinamita.
{88773}{88866}Con suficiente jabón,|se puede volar cualquier cosa.
{88869}{88916}Tyler sabía muchas cosas útiles.
{88919}{89015}La gente vio que la ropa quedaba|más limpia lavada en un lugar del río.
{89017}{89065}- ¿Sabes porqué?|- No.
{89132}{89223}Se hacían sacrificios humanos|cerca del río.
{89226}{89302}Quemaban cuerpos.|El agua hacía lejía con las cenizas.
{89305}{89365}Esto es lejía. El ingrediente clave.
{89365}{89480}Cuando se mezclaba con la grasa humana|una solución jabonosa llegaba al río.
{89482}{89533}¿Me muestras la mano, por favor?
{89708}{89739}¿Qué es esto?
{89741}{89804}Un abrasivo químico.
{89806}{89890}Dolerá muchísimo y dejará una cicatriz.
{89892}{89955}La meditación del cáncer,|podía servir ahora.
{89974}{90041}- Debes sentir el dolor.|- ¡Díos mío!
{90060}{90166}El primer jabón fue con cenizas de|un héroe como el mono que fue al espacio.
{90168}{90240}Sin dolor o sacrificio,|no tendríamos nada.
{90242}{90312}Traté de no pensar en la carne quemada.
{90314}{90391}¡Basta!|Es tu dolor, es tu mano que se quema.
{90393}{90456}Voy a mi caverna|a buscar a mi animal de fuerza.
{90458}{90554}¡No! No te comportes como esos muertos!|¡Vamos!
{90556}{90652}- ¡Ya entiendo!|- ¡No! Sufres de iluminación prematura.
{90719}{90818}¡Te estás perdiendo|el mejor momento de tu vida!
{90820}{90856}¡No es verdad!
{90859}{90930}¡Cállate!|Nuestros padres fueron modelos de Dios.
{90933}{91010}¿Si ellos nos abandonaron,|qué te dice eso de Dios?
{91034}{91158}Oye. Es posible que|tú no le gustas a Dios.
{91161}{91259}Nunca te quiso.|Es probable que te odie.
{91261}{91345}No es lo peor del mundo.|¡Nosotros no lo necesitamos a Él!
{91348}{91420}- ¡De acuerdo!|- Nada de condena y redención.
{91422}{91482}¿Dios no nos quiere? ¡Así sea!
{91484}{91592}- ¡Voy por agua!|- Con agua lo empeoras...
{91619}{91702}- El vinagre neutraliza el quemado.|- ¡Déjame, por favor!
{91705}{91755}Primero debes renunciar.
{91758}{91822}Primero tienes que saber, no temer,
{91825}{91897}saber que un día morirás.
{91899}{91952}¡No sabes como me duele!
{92045}{92148}Sólo cuando perdemos todo|somos verdaderamente libres.
{92196}{92247}Bien.
{92566}{92614}Felicitaciones.
{92616}{92686}Estás un paso más cerca del fondo.
{92760}{92832}Tyler vendía jabón|a las tiendas a $20 por barra.
{92834}{92882}Dios sabe cuanto lo cobraban.
{92885}{92961}- Es el mejor jabón.|- Gracias, Susana.
{92964}{93014}Era hermoso.
{93016}{93108}Les vendíamos a las mujeres ricas|la grasa de sus propios culos.
{93131}{93182}Llevaba su corbata amarilla.
{93184}{93239}Yo no usaba más corbata.
{93242}{93328}"La primera regla del Club|es que no se habla del Club."
{93330}{93414}Estoy dormido de nuevo.|Lo olvidé en la fotocopiadora.
{93419}{93477}"La segunda regla..." ¿Es suyo?
{93522}{93609}Póngase en mi lugar.|Tome una decisión ejecutiva.
{93611}{93669}Encuentra esto. ¿Qué hace?
{93779}{93827}Bueno, tengo que decirle,
{93829}{93918}que en su lugar tendría mucho|cuidado con quien habla de eso.
{93920}{93999}Porque la persona que escribió|eso es peligrosa.
{93999}{94107}Y ese loco podría tener|un brote psicótico
{94112}{94179}e ir de oficina en oficina
{94182}{94304}con arma semiautomática, Armalite AR10
{94304}{94412}liquidando colegas y empleados.
{94429}{94508}Quizás sea alguien|a quien conoce desde hace años.
{94510}{94584}Alguien cercano a usted.
{94587}{94668}Las palabras de Tyler salían de mi boca.
{94692}{94743}y yo era un muchacho tan bueno.
{94745}{94824}No me traiga toda la basura|que encuentre por allí.
{94918}{95004}- Contratos y Seguros.|- Se me pudre una teta.
{95028}{95088}¿Me disculpa? Debo atender este llamado.
{95239}{95325}- ¿Qué quieres decir?|- Ven. Tengo un bulto en el pecho.
{95328}{95424}- Ve al hospital.|- No puedo gastar en un médico.
{95445}{95498}No entiendo de eso, Marla.
{95500}{95541}Por favor.
{95543}{95639}No llamó a Tyler. Para ella soy neutro.
{95690}{95786}Qué bien.|Llevas comida a las ancianas.
{95788}{95838}¿Adónde están?
{95841}{95939}Lamentablemente muertas.|Yo estoy viva y soy pobre. ¿Quieres?
{95941}{95992}- No, no.|- Tomé una para ti.
{95994}{96045}Gracias por pensar en mí.
{96076}{96131}¿Qué te pasó en la mano?
{96133}{96186}Oh, nada.
{96188}{96236}¿Allí?
{96263}{96328}- ¿Sientes algo?|- No.
{96330}{96378}Asegúrate.
{96380}{96428}Estoy bien seguro.
{96431}{96479}¿No sientes nada?
{96481}{96536}No, nada.
{96572}{96642}Es un alivio. Gracias.
{96680}{96757}- De nada.|- Me gustaría retribuirte el favor.
{96757}{96807}No hay mucho cáncer de mama|en mi familia.
{96809}{96893}- Te puedo ver la próstata.|- Creo que estoy bien.
{96896}{96946}Bueno, gracias.
{97066}{97121}- ¿Nada más?|- No, nada más.
{97124}{97176}Nos vemos... por allí.
{97589}{97639}¿Cornelius?
{97641}{97699}¡Cornelius!
{97701}{97766}¡Soy yo! ¡Bob!
{97768}{97802}Hola, Bob.
{97888}{97960}- Pensamos que habías muerto.|- No, no. Sigo aquí.
{97963}{98059}- ¿Cómo estás, Bob?|- Mejor que nunca.
{98061}{98145}- ¿Verdad? ¿Aún con el grupo?|- No, no.
{98147}{98236}- Tengo algo mucho mejor ahora.|- ¿Sí, qué es?
{98253}{98298}Bueno...
{98301}{98401}La primera regla|es que no debo hablar de ello.
{98404}{98457}Y la segunda regla es
{98457}{98512}que no debo hablar de ello.
{98514}{98596}- Y la tercera regla es...|- Bob, Bob. Soy socio.
{98600}{98648}Mírame la cara, Bob.
{98706}{98763}Es maravilloso.
{98763}{98855}- Nunca te he visto allí.|- Voy martes y jueves.
{98855}{98946}- Yo voy los sábados.|- Te felicito.
{98955}{99010}¿A ti también, no?
{99013}{99075}¿Sabes algo del tipo que lo inventó?
{99080}{99150}- Sí, yo...|- Se dicen muchas cosas de él.
{99152}{99238}Se supone que nació en un manicomio
{99241}{99322}y duerme una sola hora por noche.
{99325}{99377}Es un tipo sensacional.
{99411}{99468}¿Conoces a Tyler Durden?
{100065}{100116}¿No te hice daño, verdad?
{100118}{100169}En realidad, sí.
{100171}{100219}Gracias por esto.
{100226}{100284}Gracias, gracias, gracias.
{100286}{100334}Club de Lucha.
{100336}{100387}Era el regalo de Tyler y mío.
{100391}{100439}Nuestro regalo al mundo.
{100442}{100521}Miro a mi alrededor|y veo muchas caras nuevas.
{100559}{100612}¡Cállense!
{100617}{100732}Significa que no han cumplido|las dos primeras reglas del Club.
{100933}{101029}Veo en el Club a los hombres|más listos y más fuertes.
{101032}{101082}Veo tanto potencial.
{101084}{101135}Y veo que se desperdicia.
{101159}{101233}Dios mío,|una generación vendiendo gasolina.
{101245}{101295}Sirviendo mesas.
{101298}{101348}Esclavos con cuello blanco.
{101408}{101480}Los avisos nos hacen desear|tener coches y ropas.
{101485}{101562}Hacemos trabajos odiosos|para comprar lo innecesario...
{101655}{101715}Hijos del medio de la historia.
{101715}{101765}Sin propósito ni lugar.
{101770}{101820}Sin Gran Guerra.
{101828}{101878}Sin Gran Depresión.
{101921}{101976}Nuestra gran guerra es espiritual.
{101988}{102067}La gran depresión son nuestras vidas.
{102137}{102209}Hemos crecido con la televisión|y nos han hecho creer
{102211}{102300}que seremos millonarios|y dioses de la pantalla y del rock.
{102302}{102353}Pero no es así.
{102355}{102413}Lo vamos aprendiendo de a poco.
{102415}{102475}Y estamos muy disgustados.
{102475}{102516}¡Sí!
{102609}{102691}La primera regla del Club de Lucha|es no hablar...
{102823}{102854}¿Quién es usted?
{102873}{102935}- ¿Quién soy yo?|- Sí.
{102957}{103026}Un cartel a la entrada|dice "La Taberna de Lu".
{103053}{103146}Soy Lu. ¿Quién mierda eres tú?
{103146}{103197}Tyler Durden.
{103271}{103355}¿Quién le dijo a este hijo de puta|que podía usar mi local?
{103357}{103415}Tenemos un arreglo con Irvine.
{103415}{103477}Irvine está en casa|con la clavícula rota.
{103480}{103532}No es el propietario. Soy yo.
{103583}{103667}- ¿Cuánto cobras por esto?|- No se cobra.
{103669}{103736}- Es gratis.|- ¿No es maravilloso?
{103739}{103782}Sí, lo es.
{103784}{103842}¡Mira, imbécil!
{103846}{103906}- Se van todos ya mismo.|- ¡Oiga!
{103909}{103962}Deberían asociarse al club.
{103971}{104019}¿Oíste lo que dije?
{104021}{104072}Tú y tu amigo.
{104117}{104168}¿Me oyes ahora?
{104220}{104271}No, no te oí bien, Lu.
{104417}{104465}Aún no entendí.
{104489}{104542}Si, Sí, ahora sí.
{104544}{104604}Sí, lo oí, lo oí. Y ya me lo olvidé.
{104628}{104674}¡Atrás! ¡Todos!
{104714}{104762}¡Todos atrás!
{104942}{104995}¡Ah, Lu!
{104997}{105086}¡Vamos, hombre!|Nos gusta de verdad este lugar.
{105302}{105371}- Está bien, Lu. Dale.|- Cállate la boca, mierda.
{105374}{105417}¡Oh, sí!
{105537}{105587}¿Es gracioso?
{105817}{105880}El tipo es un loco, les digo.
{105899}{105940}Increíble.
{106040}{106112}- No sabes donde he estado, Lu.|- Oh, mi Dios!
{106115}{106184}¡Te puedo contagiar!
{106258}{106330}¡Por favor, deja quedarnos, Lu!
{106333}{106393}¡Usen el sótano! ¡Cristo!
{106395}{106462}¡Dame tu palabra, Lu! ¡Dame tu palabra!
{106465}{106513}Por mi madre.
{106731}{106784}Gracias, Lu.
{106815}{106865}Tú también, grandote.
{106959}{107009}Los vemos la semana entrante.
{107381}{107467}Esta semana tienen una tarea.
{107469}{107584}Van a salir y buscar pelea|con un total desconocido.
{107663}{107714}Van a provocar una pelea
{107716}{107767}y la van a perder.
{107812}{107860}Excelente elección, señor.
{107922}{108002}¡Oiga, idiota! ¡Cuidado!
{108011}{108076}No es tan fácil como parece.
{108141}{108186}¡Hijo de puta!
{108189}{108304}La mayoría de la gente normal|hace lo posible por evitar una pelea.
{108325}{108376}¡Disculpe!
{108378}{108467}Me mojó con su manguera.|No es necesario...
{108469}{108515}¡Jay! ¡Llama a la policía!
{108579}{108630}Deja la manguera.
{108632}{108680}¡Basta! ¡Basta!
{108721}{108766}Lo siento.
{109138}{109198}Debemos hablar.
{109251}{109301}Bueno.
{109303}{109354}¿Por dónde empezar?
{109356}{109409}¿Sus constantes ausencias?
{109409}{109471}¿Su aspecto impresentable?
{109474}{109522}Le corresponde su revisión anual.
{109524}{109601}Soy la falta de sorpresa total de Jack.
{109603}{109649}- ¿Qué?|- Supongamos.
{109651}{109721}Usted es el Departamento|de Transporte. ¿Sí?
{109723}{109809}Alguien le informa que esta empresa
{109812}{109910}instala piezas delanteras|que fallaron las pruebas de choque.
{109912}{109994}Frenos que fallan a los 1.500 Km.,
{109996}{110102}e inyectores de combustible|que explotan y queman viva a la gente.
{110104}{110150}¿Y entonces?
{110150}{110205}¿Me está amenazando?
{110207}{110274}- No...|- Váyase. ¡Está despedido!
{110277}{110385}Tengo una idea mejor.|Me paga como consultor externo.
{110385}{110435}A cambio de mi sueldo,
{110438}{110529}nunca le diré a nadie lo que sé.
{110531}{110634}Ni tengo que venir a la oficina.|Puedo trabajar en casa.
{110665}{110764}¿Quién mierda se cree que es,|demente imbécil?
{110891}{110975}- ¡Seguridad!|- Soy la venganza de Jack.
{111190}{111241}¿Qué demonios está haciendo?
{111461}{111512}Eso dolió.
{111545}{111596}¿Porqué hizo eso?
{111612}{111684}¡Oh, Dios! ¡No! ¡Basta!
{111907}{111958}¿Qué está haciendo?
{111984}{112034}¡Oh, Dios, no! ¡Por favor! ¡No!
{112037}{112135}Por algún motivo,|pensé en mi primera pelea con Tyler.
{112137}{112176}¡No!
{112761}{112866}Debajo y detrás y dentro de|todo lo que este hombre daba por sentado
{112871}{112953}algo horrible había crecido.
{112955}{112981}Mire.
{112984}{113096}Págueme como le pedí y no me volverá a ver.
{113099}{113166}Entonces, en el mejor momento juntos...
{113238}{113305}¡Gracias a Dios!|No me pegue más, por favor.
{113307}{113358}Teléfono, computadora,
{113360}{113482}fax, 52 semanas de pago|y 48 cupones de vuelo.
{113485}{113542}Teníamos patrocinador empresarial.
{113545}{113670}Así fue como Tyler y yo pudimos reunir|al Club todas las noches.
{113732}{113818}Ahora el centro del Club|eran los dos luchadores.
{113821}{113904}El líder atravesaba la muchedumbre,|en la oscuridad.
{113945}{114056}Tyler estaba involucrado|en un pleito contra el Hotel Pressman
{114056}{114111}por el contenido de orina de sus sopas.
{114235}{114307}Soy la vida perdida de Jack.
{114492}{114542}Gracias, señor.
{114578}{114650}Tyler inventó nuevas tareas.
{114653}{114712}Las entregaba en sobres cerrados.
{115185}{115262}USTED PUEDE USAR ACEITE VIEJO DE|COCHE PARA FERTILIZAR SU JARDÍN
{115652}{115741}- Hay un Club de Luchas en Delaware.|- Sí, me lo dijeron.
{115784}{115837}Y otro en Penns Grove.
{115837}{115892}Bob encontró uno en New Castle.
{115895}{115966}- ¿Lo iniciaste tú?|- No, creía que lo habías hecho tú.
{115971}{116002}No.
{116746}{116782}LA POLICÍA INCAUTA|UNA CATAPULTA DE EXCREMENTO
{116815}{116856}ARTISTA ACOSADO SEXUALMENTE
{116890}{116947}MONOS APARECEN AFEITADOS
{117199}{117254}- Un segundo.|- ¿Qué hacemos?
{117256}{117304}- Date vuelta.|- ¿Qué haces?
{117307}{117364}- La tarea.|- ¿De qué tipo?
{117367}{117417}Sacrificio humano.
{117417}{117499}- ¿Es una pistola? Dime que no.|- Es una pistola.
{117501}{117556}- ¿Qué haces?|- Encuéntrame atrás.
{117558}{117616}- ¡No jodas!|- Encuéntrame atrás.
{117618}{117662}En una línea de tiempo muy larga,
{117662}{117731}el promedio de supervivencia cae a cero.
{117755}{117805}¿Qué estás haciendo? ¡Vamos!
{117808}{117889}Manos atrás. Dame tu cartera.
{117930}{118009}Raymond K Hessel.|1320 SE Banning, Apartmento A.
{118028}{118105}- ¿Pequeño apartamento en el sótano?|- ¿Cómo lo sabe?
{118108}{118170}A los apartamentos de mierda|les ponen letras.
{118172}{118247}¡Raymond! Vas a morir.
{118251}{118285}¡No!
{118287}{118386}¿Son tu papá y mamá?|Van a tener que llamar al médico.
{118390}{118443}Pedir tu foja dental. ¿Sabes porqué?
{118446}{118532}- No quedará nada de tu cara.|- ¡Oh, vamos!
{118534}{118628}Una tarjeta de estudiante vencida.|¿Qué estudiabas, Raymond?
{118630}{118702}- Cosas.|- ¿Cosas?
{118705}{118755}¿Eran difíciles los exámenes?
{118781}{118844}- ¡Te pregunté qué estudiabas!|- Biología.
{118846}{118930}- ¿Porqué?|- No sé.
{118932}{119004}¿Qué querías ser, Raymond K Hessel?
{119038}{119131}La pregunta, Raymond, era:|¿Qué querías ser?
{119172}{119222}¡Contesta, Raymond!
{119225}{119282}- Veterinario.|- Animales.
{119285}{119357}- Sí. Animales y cosas.|- Cosas. Sí, ya te oí.
{119357}{119419}- Debes estudiar más.|- Demasiado estudio.
{119421}{119481}- ¿Prefieres morir?|- No, por favor...
{119481}{119589}¿Prefieres morir, de rodillas,|detrás de una tienda?
{119592}{119630}Por favor, no.
{119728}{119779}Me guardo tu licencia.
{119807}{119879}Te voy a controlar. Sé donde vives.
{119882}{119954}Si en seis semanas no estás|estudiando veterinaria,
{119956}{120006}estás muerto.
{120052}{120102}Ahora vete a casa.
{120215}{120265}¡Corre, Forrest Gump, corre!
{120304}{120354}Me siento mal.
{120373}{120424}Imagínate como se siente él.
{120426}{120474}¡Vamos, no es gracioso!
{120476}{120536}¿Para que mierda hiciste eso?
{120536}{120637}Mañana será el día más bello|de la vida de Raymond K Hessel.
{120637}{120742}Su desayuno sabrá mejor que|cualquier comida que haya probado.
{120778}{120826}Tyler tenía razón a su manera.
{120829}{120886}- Vamos.|- Tenía un plan.
{120889}{120970}Y empezaba a tener sentido|a la manera de Tyler.
{120973}{121018}Sin miedo. Sin distracciones.
{121021}{121100}La capacidad de dejar que|aquello que no importa
{121102}{121150}resbale.
{121471}{121522}Tú no eres tu trabajo.
{121570}{121649}No eres la cantidad de dinero|que tienes en el banco.
{121690}{121740}No eres el coche que conduces.
{121752}{121821}No eres el contenido de tu cartera.
{121824}{121879}No eres tus pantalones deportivos.
{121946}{122035}Eres la mierda cantante|y danzante de este mundo.
{122248}{122299}Me voy en un momento.
{122320}{122368}No es necesario.
{122406}{122454}Lo que sea.
{122483}{122557}No, quiero decir... que está bien.
{122785}{122836}¿Siempre vas a los grupos?
{122852}{122903}Sí.
{122936}{122987}Chloe se murió.
{122999}{123047}Chloe.
{123049}{123095}¿Cuándo?
{123109}{123154}¿Te importa?
{123157}{123236}No sé. Hace mucho que no pienso en ella.
{123243}{123294}Sí, bueno...
{123296}{123351}Fue una movida inteligente de su parte.
{123385}{123433}Oye...
{123464}{123521}¿Qué sacas de todo esto?
{123538}{123588}¿Qué?
{123591}{123646}Todo esto. ¿Porqué sigues...
{123665}{123713}¿Te hace feliz?
{123752}{123802}Sí, bueno, a veces.
{123845}{123895}No sé. No entiendo.
{123898}{123982}¿Porqué un débil necesita|engancharse a un fuerte?
{123984}{124034}¿Para qué...?
{124037}{124090}¿Qué sacas de ello tú?
{124123}{124173}No... No es lo mismo para nada.
{124176}{124226}Es diferente entre nosotros.
{124253}{124279}¿Nosotros?
{124281}{124327}¿Qué quiere decir nosotros?
{124329}{124420}- Lo siento. ¿Oyes?|- Oír qué?
{124423}{124473}- Ese ruido. Espera.|- ¡No, espera!
{124473}{124540}¡No cambies el tema!|Quiero hablar de esto.
{124540}{124607}- ¿No hablan de mí, verdad?|- No.
{124610}{124694}- ¿Qué?|- Jugar al doctor. ¿Qué fue eso?
{124696}{124773}- ¿De qué hablas?|- Nada. Nada.
{124775}{124823}- No creo.|- ¿Qué quieres?
{124828}{124886}- Mírame.|- No. ¿Qué?
{124905}{124972}- ¿Qué es eso?|- Nada. No te preocupes.
{124974}{125032}Mi Dios. ¿Quién te lo hizo?
{125034}{125082}- Una persona.|- ¿Hombre o mujer?
{125085}{125152}- ¿Qué te importa?|- ¿Qué te importa si pregunto?
{125154}{125216}- Déjame tranquilo.|- Tienes miedo de decirlo.
{125219}{125267}- No. Déjame.|- ¡No! Háblame.
{125269}{125296}¡Suéltame!
{125298}{125363}- Esta conversación...|- Esta conversación...
{125365}{125425}- ..se acabó.|- ..se acabó.
{125447}{125519}¿Nunca puedo acertar contigo, no?
{125744}{125804}Esta situación se repite demasiado.
{125818}{125873}¿Qué es esto... Qué es esto?
{125876}{125926}¿Qué crees?
{125948}{125998}¿Para qué tantas camas?
{126000}{126044}¡Oye!
{126209}{126252}Demasiado joven.
{126255}{126295}Lo siento.
{126298}{126346}¿Qué es todo esto?
{126348}{126420}Si el candidato es joven,|dile que es demasiado joven.
{126422}{126485}- Si es viejo, demasiado viejo.|- ¿Candidato?
{126487}{126566}Si el candidato espera tres días|sin alimentos ni techo,
{126569}{126619}entra y comienza a entrenarse.
{126621}{126665}¿Entrenarse para qué?
{126799}{126849}¿Crees que es un juego?
{126852}{126916}Eres demasiado joven y se acabó.
{126916}{126984}No nos hagas perder tiempo.|Vete a la mierda.
{127077}{127127}Malas noticias, amigo.
{127135}{127183}No sucederá.
{127185}{127240}Siento el malentendido.
{127242}{127288}No es el fin del mundo.
{127290}{127343}Vete.
{127365}{127413}Vete.
{127415}{127504}Estás violando mi espacio|y tendré que llamar a la policía.
{127578}{127626}¡No me mires!
{127628}{127708}¡No entrarás nunca en esta casa!
{127710}{127789}Nunca. ¡Ahora vete de mi puerta!|¡Sal de aquí!
{127791}{127878}Tarde o temprano, todos nos convertíamos|en lo que Tyler quería.
{127880}{127947}Voy a entrar y traer una pala.
{128130}{128182}- ¿Dos camisas negras?|- Sí, señor.
{128182}{128237}- ¿Dos pantalones negros?|- Sí, señor.
{128240}{128312}- ¿Botas negras? ¿Calcetines?|- Sí, señor.
{128312}{128362}- Una chaqueta negra.|- Sí, señor.
{128365}{128436}- ¿$300 para tu propio entierro?|- Sí, señor.
{128489}{128537}Bien.
{128775}{128822}Eres demasiado viejo, gordo.
{128825}{128902}Tus tetas son grandes.|Vete de mi casa.
{129089}{129139}¡Bob! ¡Bob!
{129523}{129585}Como el mono listo|para el cohete espacial.
{129604}{129640}Mono espacial.
{129642}{129726}Dispuesto al sacrificio|por el bien de la humanidad.
{129885}{129949}¡Eres demasiado viejo, gordito!
{129949}{130026}Y tú... Eres demasiado...
{130028}{130069}..rubio!
{130069}{130127}¡Váyanse a la mierda los dos!
{130127}{130180}Y así siguió.
{130182}{130232}Escuchen, gusanos.
{130235}{130285}No son especiales.
{130295}{130374}No son bellos ni únicos.
{130376}{130479}Son todos la misma materia orgánica.
{130482}{130532}Tyler se formó un ejército.
{130539}{130625}Somos la mierda cantante|y danzante del mundo.
{130628}{130714}Somos todos la misma pila de estiércol.
{130741}{130817}¿Porqué Tyler Durden|formaba un ejército?
{130820}{130870}¿Con qué propósito?
{130870}{130930}¿Para qué beneficio?
{131009}{131059}En Tyler confiábamos.
{131187}{131251}Cuando decía,|"No son su trabajo",
{131254}{131304}yo decía: "¡Sí!"
{131347}{131398}¿Qué es todo esto?
{131400}{131450}¡Oye!
{131486}{131527}¡Bien!
{131529}{131585}- ¿Qué sucede?|- Celebramos.
{131587}{131647}- ¿Qué celebramos?|- Vamos.
{131743}{131796}- Oye.|- Déjame que te ayude.
{131906}{131975}Siempre el mismo sabor, Pepsi.
{131978}{132028}NOTICIERO
{132088}{132179}Los investigadores están aquí.|Ha llegado el Jefe de Policía.
{132182}{132251}¿Qué cree que ha sucedido aquí?
{132253}{132354}Es uno de los muchos recientes|actos de vandalismo en la ciudad
{132357}{132433}vinculados con clubes|clandestinos de boxeo
{132436}{132536}Coordinaremos|una investigación rigurosa.
{132558}{132661}Fue el Jefe de Policía Jacobs|quien acaba de llegar al lugar
{132666}{132767}- del incendio que se originó...|- La chica tiene lo suyo.
{132769}{132812}Al estudio.
{132815}{132872}- ¡Sí!|- ¡Sí!
{132896}{132956}- ¡Mierda!|- ¡Sí!
{133131}{133179}¿Qué mierda hicieron ustedes?
{133181}{133280}Los investigadores especialistas|en incendios se encuentran...
{133371}{133479}La primera regla del Proyecto Caos|es que no se hacen preguntas, señor.
{133627}{133687}La victoria contra el crimen
{133690}{133740}no será de la noche a la mañana.
{133742}{133853}Requerirá compromiso y entrega|y sobre todo cooperación.
{133853}{133973}Las calles son más seguras ahora.|Hay esperanza en el casco urbano...
{133973}{134021}Voy a orinar.
{134023}{134090}..son los primeros pasos|de un largo camino.
{134092}{134155}Por eso hemos creado|el Proyecto Esperanza.
{134155}{134205}Bob.
{134282}{134347}El Proyecto Esperanza|es un esfuerzo conjunto
{134349}{134416}entre la policía|y los líderes de la comunidad.
{134419}{134517}Será un arma nueva y poderosa|en la guerra contra el crimen.
{135608}{135706}- Envuélvele las bolas.|- Las tiene heladas.
{135754}{135833}Vas a cancelar|tu rigurosa investigación.
{135836}{135917}Declararás en público|que no existe el grupo clandestino
{135919}{135975}o te cortarán las bolas.
{135996}{136087}Enviarán una al New York Times|y la otra al LA Times.
{136090}{136130}Mira.
{136133}{136207}La gente que persigues|es la gente de la que dependes.
{136210}{136293}Cocinamos. Juntamos la basura.|Conectamos las llamadas.
{136296}{136387}Conducimos las ambulancias.|Te cuidamos mientras duermes.
{136492}{136560}No jodas con nosotros.
{136737}{136787}¡Fíjate si tus bolas siguen allí!
{137133}{137183}Bob, por aquí.
{137209}{137265}Vamos.
{137267}{137344}Soy el sentido de rechazo de Jack.
{137370}{137418}¡Eh!
{137768}{137797}¡Sí!
{138583}{138650}Quería matara cada panda
{138653}{138744}que no se pareara para salvara su especie.
{138797}{138861}Abrir las válvulas|de los buques petroleros
{138864}{138933}y arruinar playas de Francia|que nunca vería.
{139012}{139072}Quería respirar humo.
{139487}{139540}¿En qué pensabas, psicópata?
{139581}{139650}Quería destruir algo bello.
{139734}{139784}Al hospital.
{139787}{139837}Sí.
{140096}{140168}No se preocupe, Sr. Durden.|Parqueo del Aeropuerto. Larga duración
{140204}{140254}Usted primero, Sr. Durden.
{140278}{140329}Usted primero.
{140470}{140520}RECICLE A SUS ANIMALES
{140753}{140815}- ¿Algo te preocupa, querido?|- No.
{140818}{140895}Sí. ¿Porqué no se me dijo|del Proyecto Caos?
{140897}{140969}La primera regla del Proyecto|es no hacer preguntas.
{140971}{141029}¿Porqué no participé|desde el principio?
{141031}{141156}El Club de Lucha fue el principio.|Ahora es el Proyecto Caos.
{141158}{141264}Empezamos el Club juntos. ¿Recuerdas?|Era tan mío como tuyo.
{141264}{141367}- ¿Hablas sobre nosotros?|- Sí. ¿No hacíamos esto juntos?
{141369}{141451}Esto no nos pertenece.|No somos especiales.
{141453}{141513}Mierda. Deberías habérmelo dicho.
{141532}{141580}¡Oye, Tyler!
{141623}{141683}- ¡Demonios, Tyler!|- ¡¿Qué quieres?!
{141686}{141746}¿Una declaración de intención?|¿Un correo electrónico?
{141748}{141810}- Oh...|- ¡Tu decides tu nivel de participación!
{141813}{141878}¡Quiero saber algunas cosas primero!
{141878}{141942}- La primera regla del Proyecto...|- ¡Cállense!
{141983}{142074}- Quiero saber qué estás pensando.|- ¡Olvida lo que sabes!
{142074}{142158}Olvida lo que crees que sabes|de la vida, la amistad,
{142160}{142211}y especialmente de ti y sobre mí.
{142237}{142290}¿Y eso qué significa?
{142371}{142424}¿Qué haces?
{142446}{142510}¿Qué desearían haber hecho|antes de morir?
{142513}{142582}- Pintar un autorretrato.|- Construir una casa.
{142585}{142640}- ¿Y tú?|- No sé. Nada.
{142642}{142700}- Ve por tu carril.|- ¡Tienes que saber!
{142702}{142777}¿Si murieras ahora,|que pensarías de tu vida?
{142779}{142865}¡No sé! Nada bien.|¿Es eso lo que quieres oír?
{142868}{142923}- ¡Vamos!|- Insuficiente.
{142925}{142983}¡Déjate de joder! ¡Tyler!
{143033}{143067}¡Jesús!¡Cristo!
{143086}{143136}¡Maldito! ¡Vete a la mierda!
{143139}{143187}¡A la mierda con el Club y con Marla!
{143189}{143254}¡Estoy harto de toda tu mierda!
{143256}{143302}Bueno, hombre.
{143345}{143405}- Déjate de joder. ¡Conduce!|- ¡Mírenlo!
{143407}{143474}- ¡Conduce!|- Mírenlo. ¡Eres lamentable!
{143477}{143599}- ¿Porqué? ¿De qué hablas?|- ¿Porqué crees que volé tu apartamento?
{143613}{143649}¿Qué?
{143652}{143745}Tocar fondo no es un fin de semana.|No es un seminario.
{143748}{143836}¡Déjate de controlar todo|y abandónate!
{143880}{143923}¡Suéltate!
{143925}{143975}Muy bien. Bueno.
{143997}{144043}Bueno.
{145443}{145503}No había estado nunca en un accidente.
{145503}{145587}Así se deben haber sentido|todas esas personas
{145589}{145666}que yo convertí|en estadísticas de mis informes.
{145666}{145716}¡Maldición!
{145800}{145877}¡Acabamos de tener|una experiencia vital!
{145968}{146016}En el mundo que veo,
{146018}{146112}cazarás ciervos|en la floresta del Gran Cañón
{146114}{146186}alrededor de las ruinas|del Centro Rockefeller.
{146234}{146339}Vestirás ropa de cuero|que te durará toda la vida.
{146342}{146450}Escalarás las viñas de kudzu|que envuelven la Torre Sears.
{146452}{146562}Y cuando mires hacia abajo verás|diminutas figuras moliendo maíz
{146562}{146649}poniendo tiritas de venado...|en los carriles
{146651}{146706}..de alguna carretera abandonada.
{147028}{147080}Que te sientas mejor, campeón.
{147498}{147541}Y luego...
{147543}{147579}¿Tyler?
{147581}{147632}..Tyler se había ido.
{147809}{147857}¿Estaba dormido?
{147884}{147932}¿Me había dormido?
{147936}{148008}No son bellos ni únicos...
{148011}{148068}La casa estaba viva.
{148071}{148181}Húmeda de tanto sudor y respiración.
{148193}{148255}Había tanta gente que la casa se movía.
{148325}{148375}Planeta Tyler.
{148377}{148425}Yo abrazaba los muros.
{148428}{148502}Atrapado dentro de esta máquina|de monos espaciales.
{148505}{148596}¡No se fuma aquí!|¡Hay demasiado éter!
{148598}{148658}Se cocinaba, trabajaba|y dormía en equipo.
{148713}{148761}Espera un momento.
{148929}{148967}DESINFORMACIÓN|MALICIA
{149217}{149281}Está bajo control, señor.
{149339}{149384}¿Dónde está Tyler?
{149384}{149456}Señor, la primera regla|del Proyecto es que no se...
{149461}{149507}Bien....Bueno.
{149564}{149615}Estoy solo.
{149619}{149706}Mi padre me abandonó. Tyler me abandonó.
{149711}{149763}Soy el corazón partido de Jack.
{149864}{149955}Cómo sigue el Proyecto...|sólo Tyler lo sabe.
{149977}{150053}La segunda regla es que no se pregunta.
{150121}{150185}¡Déjame tranquilo!|¡Déjame tranquilo!
{150195}{150245}¿Quién es toda esta gente?
{150370}{150425}Compañía Jabonera Calle del Papel.
{150463}{150514}¿Puedo entrar?
{150588}{150638}No está aquí.
{150638}{150694}¿Qué?
{150718}{150804}Tyler no está.
{150806}{150854}Tyler se fue.
{150866}{150917}Tyler se fue.
{151324}{151365}¡Consigue ayuda!
{151633}{151751}¡Recibió dos balazos!|¡Dejen pasar!
{151751}{151808}¿Qué sucedió? ¿Qué sucedió?
{151811}{151880}Una misión.|Matar dos pájaros de un tiro.
{151912}{151962}Destruir una obra de arte corporativo...
{151964}{152024}Operación Leche Trueno. ¡Ya!
{152041}{152118}..y destruir el café de una cadena.
{152271}{152326}Todo estaba arreglado, señor.
{152523}{152602}- Fue bien hasta que...|- ¡Policía! ¡No se muevan!
{152604}{152669}- ¿Qué?|- Mataron a Bob.
{152705}{152765}- Dos tiros a la cabeza.|- ¡Hijos de puta!
{152892}{152943}¡Oh, Dios!
{152943}{153022}- ¡Esos cabrones!|- Imbéciles.
{153024}{153122}¿Andan por allí con máscaras|intentando volar cosas?
{153125}{153190}¿Qué creían que iba a suceder?
{153230}{153336}¡Rápido! Desháganse de la evidencia.|¡Hay que deshacerse del cadáver!
{153338}{153408}- Entiérrenlo.|- ¿Qué?
{153408}{153463}Entiérrenlo en el jardín.
{153465}{153535}- ¡Vamos, gente, vamos!|- ¡No se acerquen!
{153537}{153614}¡No se le acerquen!|¿De qué hablan?
{153616}{153679}Esto no es la evidencia.|Es una persona.
{153681}{153758}Es mi amigo.|¡Y no lo enterrarán en el jardín!
{153758}{153830}Murió al servicio del Proyecto Caos.
{153832}{153882}- Este es Bob.|- Señor, en...
{153882}{153935}En el Proyecto no tenemos nombre.
{153935}{153983}Escuchen.
{153986}{154093}Este es un hombre y tiene nombre,|y es Robert Paulsen. ¿De acuerdo?
{154096}{154141}- Robert Paulsen.|- Es un hombre.
{154144}{154213}y está muerto por culpa nuestra.|¿Lo entienden?
{154228}{154283}Entiendo.
{154338}{154419}Al morir, un miembro del Proyecto Caos
{154419}{154470}tiene nombre.
{154472}{154544}Su nombre es Robert Paulsen.
{154554}{154604}Su nombre es Robert Paulsen.
{154623}{154688}Su nombre... es Robert Paulsen.
{154688}{154774}Su nombre es Robert Paulsen.
{154777}{154817}Vamos. Basta. Acábenla.
{154858}{154921}Su nombre es Robert Paulsen.
{154947}{154997}¡Cállense! ¡Esto se acabó!
{155074}{155134}Váyanse.
{155822}{155930}- ¿Tyler?|- No, Detective Stern de Incendios.
{155932}{155968}Necesito verle...
{156079}{156175}Fui a todas las ciudades de los|cupones de Tyler de bar en bar...
{156177}{156292}Podía visitar 50 bares distintos|y saber si había estado Tyler.
{156292}{156402}Busco a Tyler Durden.|Es muy importante que le hable.
{156405}{156445}Desearía poder ayudarle,
{156445}{156503}señor.
{156628}{156678}En cada ciudad que visité,
{156704}{156762}apenas bajaba del avión
{156776}{156831}sabía si había un Club de Lucha.
{156834}{156872}¡Oiga!
{156899}{156937}¡Taxi!
{156939}{156990}Mírenme la cara. Soy socio.
{156992}{157052}Necesito saber si han visto a Tyler.
{157054}{157143}No puedo brindarle|dicha información...
{157146}{157258}..pero no lo haría tampoco|si tuviera dicha información.
{157275}{157361}- Imbécil.|- Le voy a pedir que se retire.
{157395}{157515}Tyler había abierto sucursales|del Club en todo el país.
{157582}{157690}¿Había estado dormido?|¿Me había dormido?
{157690}{157745}¿Tyler es mi pesadilla|o soy yo la suya?
{157779}{157853}- Hemos oído historias.|- ¿Qué tipo de historias?
{157853}{157956}- Nadie sabe qué aspecto tiene.|- Se hace cirugía plástica cada 3 años.
{157958}{158030}Es lo más estúpido que he oído jamás.
{158033}{158131}- ¿Es verdad lo del Club en Miami?|- ¿El Sr. Durden tiene un ejército?
{158133}{158205}Vivía en estado de perpetuo déjà vu.
{158225}{158275}Dondequiera que fuera,
{158277}{158325}sentía que él ya había estado allí.
{158328}{158397}Era como seguir a un hombre invisible.
{158424}{158471}El olor a sangre seca,
{158474}{158558}huellas de pies sucios.
{158579}{158656}El aroma del sudor rancio|como de pollo frito.
{158658}{158742}El piso aún tibio de la pelea|de la noche anterior.
{158764}{158834}Estaba siempre un paso detrás de Tyler.
{158903}{158980}Su nombre es Robert Paulsen...
{159090}{159140}Bienvenido, señor.
{159164}{159212}¿Cómo ha estado?
{159215}{159267}¿Me conoce?
{159270}{159327}¿Es una prueba, señor?
{159330}{159373}No. No es una prueba.
{159375}{159431}Usted vino el jueves pasado.
{159443}{159498}¿Jueves?
{159500}{159596}Estaba de pie allí mismo|y preguntó si la seguridad era buena.
{159610}{159661}Es excelente, señor.
{159725}{159776}¿Quién cree que soy?
{159778}{159841}¿Seguro que no es una prueba?
{159843}{159888}No, no es una prueba.
{159891}{159939}Usted es el Sr. Durden.
{159972}{160037}Usted me hizo esto.
{160037}{160138}Coloquen sus asientos|en la posición vertical.
{160414}{160464}- ¿Sí?|- Marla, soy yo.
{160464}{160512}- ¿Lo hemos hecho?|- ¿Hecho qué?
{160514}{160545}¿Sexo juntos?
{160548}{160601}¿Qué pregunta estúpida es esa?
{160603}{160660}¿Estúpida porque es sí,|o porqué es no?
{160663}{160723}- ¿Es un truco?|- No. Necesito saber...
{160728}{160819}¿Quieres saber si pienso que|era sexo o si hacíamos el amor?
{160821}{160903}- ¿Hicimos el amor?|- ¿Lo llamas así ahora?
{160905}{160972}¡Contesta la pregunta!|¿Lo hicimos o no?
{160975}{161044}Me la metes y me dejas.|Me amas y me odias.
{161047}{161116}Eres decente y te vuelves un hijo de puta.
{161118}{161183}¿Describo mejor nuestra relación, Tyler?
{161183}{161234}La cabina ha perdido la presión.
{161236}{161272}¿Qué dijiste?
{161274}{161329}- ¿Qué te pasa?|- ¡Di mi nombre!
{161332}{161421}¡Tyler Durden! ¿Qué sucede?
{161423}{161471}- ¡Voy a tu casa!|- ¡No estoy en casa!
{161521}{161591}- Acabas de romper tu promesa.|- Jesús, Tyler.
{161593}{161675}- Hablaste con ella sobre mí.|- ¿Qué mierda pasa?
{161677}{161761}Te pedí una cosa. Una cosa sencilla.
{161763}{161819}¿Porqué la gente cree que soy tú?
{161831}{161881}¡Responde!
{161938}{161982}Siéntate.
{162049}{162113}Responde.|¿Porqué creen que soy tú?
{162116}{162169}Yo creo que lo sabes.
{162171}{162233}- No, no lo sé.|- Sí que lo sabes.
{162236}{162300}¿Porqué se me confundiría contigo?
{162303}{162370}No lo sé.
{162485}{162552}- Te diste cuenta.|- No.
{162555}{162605}- ¡No jodas con nosotros!|- Dilo.
{162639}{162686}Porque...
{162720}{162749}¡Dilo!
{162787}{162838}Porque somos la misma persona.
{162840}{162890}Eso es.
{162893}{162943}Somos la mierda cantante y danzante.
{162945}{163034}- No lo entiendo.|- Tú querías cambiar tu vida.
{163037}{163087}No lo podías lograr solo.
{163089}{163137}Todo lo que deseabas ser,
{163142}{163185}eso soy yo.
{163188}{163264}Tengo el aspecto que deseas,|lo hago como querrías tu.
{163267}{163322}Soy listo, capaz y lo más importante,
{163324}{163391}soy libre como no lo eres tú.
{163391}{163415}Oh, no.
{163418}{163487}- Tyler no está. Tyler se fue.|- ¿Qué?
{163490}{163545}No es posible. Es una locura.
{163547}{163598}La gente lo hace todo el tiempo.
{163598}{163684}Se hablan a sí mismos.|Se ven como querrían ser.
{163686}{163763}No tienen el coraje tuyo|de dejarte llevar por ello.
{163857}{163936}Aún luchas contra ello,|entonces aún eres tú.
{163938}{164051}- Deberíamos volver a hacer esto.|- A veces imaginas que me estás observando.
{164053}{164113}Si es la primera vez,|tienen que pelear...
{164115}{164221}De a poco,|te estas dejando convertir en...
{164240}{164286}Tyler Durden.
{164288}{164355}¡No son su trabajo|ni cuánto dinero tienen!
{164358}{164415}- Tú tienes casa.|- Alquilada a tu nombre.
{164418}{164504}- Tienes trabajos, vives.|- Trabajas de noche porque no duermes.
{164506}{164549}O fabricas jabón.
{164552}{164669}- Te la tiras a Marla, Tyler.|- Eres tú. A ella le da lo mismo.
{164712}{164760}Oh, mi Dios.
{164784}{164835}Ahora ves nuestro dilema.
{164837}{164890}Ella sabe demasiado.
{164892}{165015}Creo que compromete nuestras metas.
{165019}{165070}¿Qué... Qué estás diciendo?
{165091}{165194}Esto no es posible,|me niego a oírlo!
{165197}{165259}- ¡Estás loco!|- No. Tú estás loco.
{165262}{165326}No tenemos tiempo para esta mierda.
{165362}{165415}Se denomina el cambio.
{165417}{165468}La película sigue
{165470}{165544}y nadie del público tiene idea.
{165856}{165945}- ¡Señor! ¿Nos deja?|- Sí. La cuenta.
{165945}{166005}¿Me firma estos llamados telefónicos?
{166110}{166206}- ¿De cuándo son?|- Entre las 2.00 y 3.30 de esta mañana.
{166348}{166446}¿Me he ido a la cama más temprano?|¿He dormido hasta más tarde?
{166448}{166566}¿He sido Tyler durante más tiempo?
{166626}{166683}¿Hay alguien aquí?
{166748}{166798}Déjà vu otra vez.
{166837}{166897}Con bastante jabón|se puede volar todo.
{166952}{167002}Oh, mi Dios.
{167096}{167153}- 1888.|- ¿A quién llamo?
{167163}{167252}1888 Franklin. Mantenimiento. ¿Hola?
{167280}{167319}¿Hola?
{167319}{167371}¿1888 Franklin Street?
{167371}{167422}Sí. ¿Qué desea?
{167482}{167544}- ¿Hola?|- Sí, sí.
{167544}{167606}Necesito hablar con el supervisor.
{167606}{167659}- soy yo.|- Bien, escuche.
{167659}{167736}Algo terrible sucederá en su edificio.
{167738}{167789}Está bajo control, señor.
{167798}{167885}- ¿Disculpe?|- No se preocupe. Estamos bien, señor.
{167985}{168019}2160.
{168201}{168261}¡Marla! ¡Marla! ¡Espera!
{168302}{168369}¡Espera! ¡Tengo que hablarte!|¡Marla! ¡Marla!
{168371}{168470}¡Tus pelados me pegaron con una escoba!|¡Casi me rompen un brazo!
{168474}{168539}Se estaban quemando los dedos con lejía.
{168541}{168635}Esto requiere un gran acto de fe|de tu parte pero escúchame bien.
{168637}{168733}- Aquí viene un avalancha de caca.|- Un poco más de fe.
{168810}{168872}No quiero oír nada que digas tú.
{168875}{168925}Tienes todo el derecho...
{168939}{168985}Un café, gracias.
{168987}{169057}Lo que ordene es gratis, señor.
{169059}{169107}¿Porqué es gratis?
{169110}{169160}- No preguntes.|- Lo que sea.
{169160}{169294}Tomaré la sopa, pollo frito|con papas y la torta de chocolate.
{169294}{169345}Comida limpia, por favor.
{169347}{169419}En ese caso, no tome la sopa.
{169421}{169472}Nada de sopa. Gracias.
{169508}{169560}Tienes 30 segundos.
{169625}{169685}He estado extraño. ¿Verdad?
{169688}{169771}- Parece que tuviera dos lados...|- ¿Dos lados?
{169771}{169894}- Eres el Dr. Jekyll y el Sr. Mierda.|- Pero he descubierto algo importante.
{169896}{169992}- ¿Qué?|- Nuestra relación no me era clara
{169994}{170052}por motivos que no quiero hablar ahora.
{170054}{170117}- Sé que no te he tratado bien.|- O lo que sea.
{170117}{170184}No, no. ¡Quince segundos!
{170184}{170239}Quince segundos,|no abras la boca.
{170241}{170292}Quiero decirte que lo siento.
{170294}{170397}He descubierto que|realmente me gustas, Marla.
{170400}{170450}¿Ah, sí?
{170452}{170498}De verdad.
{170500}{170603}Me importas y no quiero que|te pase nada malo por mi culpa.
{170606}{170671}Marla, tu vida está en peligro.
{170673}{170719}¿Qué?
{170721}{170810}Debes irte de aquí.|No debes ir a ninguna ciudad.
{170812}{170879}- Vete al campo...|- Eres un demente.
{170882}{170963}- Te he involucrado en algo terrible.|- No. ¡Cállate!
{170965}{171028}- Estás en peligro.|- ¡Cállate!
{171071}{171176}- Escucha, Tyler. De veras lo intenté.|- Yo lo sé.
{171179}{171251}Hay cosas tuyas que me gustan.|Eres listo, divertido.
{171253}{171301}Sensacional en cama.
{171304}{171337}Pero...
{171339}{171390}eres intolerable.
{171392}{171452}Tienes graves problemas emocionales.
{171455}{171548}Problemas arraigados.|Necesitas ayuda profesional.
{171550}{171646}- Lo sé y lo siento.|- Lo sientes, lo siento, lo sentimos.
{171673}{171723}No puedo seguir contigo.
{171726}{171776}No puedo.
{171776}{171826}Y no lo haré.
{171829}{171877}Me voy.
{171879}{171944}¡No puedes irte, Marla!|¡Estás en peligro!
{172013}{172076}- ¡Marla, no entiendes!|- ¡Déjame tranquila!
{172078}{172138}- ¡Quiero protegerte!|- ¡Suéltame!
{172140}{172212}- ¡No quiero volver a verte!|- Muy bien...
{172215}{172265}¡Espera aquí!
{172358}{172421}¡Quédate allí! ¡Cállense!
{172421}{172474}Toma este dinero y vete en el bus.
{172474}{172526}Te prometo que no te fastidiaré más.
{172529}{172565}¡Cállense!
{172565}{172641}Te ruego que subas al bus.
{172670}{172721}¿Porqué lo haces?
{172723}{172821}Creen que eres peligrosa.|No te lo puedo explicar. ¡Confía en mí!
{172824}{172929}- Si sé donde estás, no estás a salvo.|- Lo cobro como impuesto a la estupidez.
{172929}{173035}- Bien. Recuerda, lejos de las ciudades.|- Tyler.
{173073}{173140}Eres lo peor que|me sucedió en la vida.
{173500}{173564}Hola. Necesito que me arresten.
{173567}{173634}Soy el líder de una banda terrorista
{173634}{173754}responsable de múltiples actos|de vandalismo en toda la ciudad.
{173756}{173850}En el área metropolitana,|tenemos 200 socios.
{173850}{173941}Sucursales en cinco o seis|ciudades principales.
{173946}{174018}Se trata de una organización
{174020}{174154}con células que operan|independientes del líder.
{174157}{174250}Vayan a la Calle del Papel 1537.
{174253}{174298}Es el cuartel general.
{174301}{174363}Enterrado en el jardín,
{174365}{174437}encontrarán a Robert Paulsen.
{174440}{174519}En el sótano, encontrarán tinas
{174521}{174648}para fabricar nitroglicerina.
{174651}{174701}El plan es volar
{174701}{174775}las compañías de tarjetas de crédito.
{174778}{174828}Y el edificio de TRW.
{174850}{174931}¿Porqué esos edificios?|¿Porqué tarjetas de crédito?
{174934}{175020}Se borran los registros|y todos quedamos en cero.
{175041}{175089}El caos total.
{175128}{175207}Que siga hablando.|Voy a hacer un llamado.
{175459}{175514}Admiro lo que hace.
{175523}{175574}¿Qué?
{175576}{175626}Es un valiente.
{175626}{175670}Es un genio, señor.
{175672}{175785}Dijo que si alguien obstaculiza|el Proyecto Caos, incluido usted,
{175787}{175845}había que cortarle las bolas.
{175878}{175953}- No luche.|- Es un gesto fuerte, Sr. Durden.
{175957}{176029}- Dará el ejemplo.|- ¡Cometen un grave error!
{176032}{176099}- Dijo que diría eso.|- ¡Yo no soy Tyler Durden!
{176101}{176195}- Dijo que diría eso también.|- Bueno. Soy Tyler Durden.
{176197}{176262}Escuchen.|Les doy una orden directa.
{176264}{176363}- Aborten esta misión ahora mismo.|- Dijo que diría eso.
{176509}{176595}¿Están todos locos?|¡Son oficiales de policía!
{176614}{176665}¿Alguien lo está cronometrando?
{176689}{176739}Cállese la boca.
{176741}{176792}¡Mierda!
{176856}{176924}La información es válida.
{176924}{177003}- Vamos a la calle del Papel.|- Enseguida.
{177019}{177063}¡Eh, esperen!
{177079}{177139}- Lo tengo.|- Señor debemos hacer esto.
{177142}{177202}- ¡Deje de resistir!|- ¿Adónde está la goma?
{177204}{177264}¡Déjenme! ¡Dejen ese cuchillo!
{177348}{177432}¡La cara contra el suelo ahora mismo!
{177461}{177509}¡Al suelo!
{177624}{177693}¡Al primero que salga por esa puerta
{177696}{177744}lluvia de balas! ¿Entendieron?
{178341}{178389}No se acerquen.|¡Quédense allí!
{178698}{178748}Corrí.
{178760}{178861}Hasta que mis músculos ardían|y mis venas eran de ácido.
{178923}{178974}Y entonces corrí más.
{179093}{179141}CALLE FRANKLIN
{179949}{180005}¿Qué demonios hace?
{180007}{180079}¡Corriendo en calzoncillos!|¡Parece loco!
{180081}{180156}Sé lo que está sucediendo aquí.
{180158}{180275}Ven. Tenemos una vista espléndida.|Es como la televisión por cable.
{180786}{180834}ESCALERA MECÁNICA DEL GARAJE
{181424}{181489}- Oh, Cristo.|- ¿Y ahora qué haces?
{181491}{181573}- Impido esto.|- ¿Porqué?
{181575}{181656}- Lo más importante de tu vida.|- No puedo permitirlo.
{181656}{181736}Hay otras 10 bombas|en otros 10 edificios.
{181738}{181793}¿El Proyecto es para asesinar?
{181796}{181843}Los edificios están vacíos.
{181846}{181913}No matamos a nadie.|¡Los liberamos!
{181915}{181983}Bob está muerto. Una bala en la cabeza.
{181985}{182064}Para hacer tortilla,|hay que romper algunos huevos.
{182066}{182153}No. No te escucho.|Ni siquiera estás allí.
{182299}{182405}Yo no haría eso.|No sabes cuál cable es cuál.
{182405}{182448}Si tú sabes, lo sé yo.
{182582}{182685}Sabía que tú sabrías y pasé|el día pensando en los que no son.
{182889}{182915}¿Crees?
{182963}{183014}Oh, cielos, no. El verde no.
{183035}{183107}No arranques el verde.
{183220}{183284}¡Te pedí que no lo hicieras!
{183328}{183366}¡Mierda!
{183388}{183438}Tyler, aléjate del camión.
{183491}{183572}¡Tyler, no bromeo! ¡Aléjate!
{183575}{183608}¡Demonios!
{183637}{183697}¡Ja! ¡Ja!
{183759}{183793}Bien.
{183795}{183874}Estás disparando|a tu amigo imaginario.
{183877}{183939}¡2.000 litros de nitroglicerina!
{183992}{184035}¡Calma, Tyler!
{184351}{184402}¡Vamos!
{184402}{184452}¡No te vayas!
{185354}{185382}¿Qué?
{186471}{186509}Tres minutos.
{186512}{186567}Es el momento.
{186569}{186617}El principio.
{186620}{186667}Nivel cero.
{186667}{186723}Aquí empezó la historia.
{186725}{186785}¿Tienes un discurso para la ocasión?
{186833}{186859}¿Qué dices?
{186862}{186912}Aún no se me ocurre nada.
{186960}{187010}Humor retroactivo.
{187133}{187181}Se pone emocionante ahora.
{187219}{187262}Dos y medio.
{187265}{187324}Piensa en todo lo que hemos logrado.
{187327}{187442}Por estas ventanas veremos el colapso|de la memoria financiera.
{187444}{187533}Un paso más cerca|al equilibrio económico.
{187859}{187917}¿Qué hace ella aquí?
{187919}{187965}Atando cabos.
{187967}{188039}¡Déjame, pelado de mierda!
{188044}{188118}- Te ruego, no hagas esto.|- Yo no lo estoy haciendo.
{188120}{188202}- Lo estamos haciendo. Lo queremos.|- No.
{188204}{188317}- Yo no lo quiero.|- Pero tú no tienes sentido ahora.
{188319}{188415}- Tenemos que olvidarnos de ti.|- Eres una voz dentro de mi cabeza.
{188418}{188468}¡Tú eres una voz en la mía!
{188471}{188538}- ¿Porqué no me puedo liberar de ti?|- Me necesitas.
{188540}{188590}No. Ya no.
{188590}{188693}Tú me creaste. Yo no cree un alter ego|perdedor para sentirme mejor.
{188696}{188792}- Acepta la responsabilidad.|- La acepto. Soy responsable...
{188794}{188835}..y lo acepto.
{188837}{188933}Te ruego. Cancela esto.
{188981}{189034}¿Nos he defraudado alguna vez?
{189070}{189125}¿Hasta dónde llegaste gracias a mí?
{189267}{189317}Lograré que salgamos ilesos de esto.
{189317}{189408}Como siempre,|te arrastraré por la fuerza
{189410}{189470}y al final me agradecerás.
{189482}{189542}Tyler. Tyler.
{189545}{189629}Te agradezco.|Por todo lo que has hecho por mí.
{189631}{189696}Pero esto es demasiado. No lo quiero.
{189696}{189823}¿Qué quieres? ¿Tu trabajo de mierda?|¿El apartamento, las telenovelas?
{189825}{189876}¡Vete a la mierda! No lo haré.
{189895}{189988}- Esto no puede estar sucediendo.|- ¡Ya sucedió, de modo que cállate!
{189988}{190029}60 segundos.
{190041}{190091}No.
{190137}{190204}No lo entiendo. No es real.
{190204}{190293}Tú no eres real, esa pistola...|Esa pistola no está en tu mano.
{190329}{190379}La pistola está en mi mano.
{190499}{190559}Pero no cambia nada.
{190772}{190835}¿Porqué te pones la pistola a la cabeza?
{190837}{190887}No a mi cabeza, Tyler.
{190902}{190950}Nuestra cabeza.
{190986}{191036}Interesante.
{191108}{191173}¿Adónde vas con esto, chico Ikea?
{191328}{191400}Tú y yo.
{191465}{191515}¿Amigos?
{191535}{191585}Tyler,
{191667}{191722}..quiero que me escuches.
{191726}{191784}Bueno.
{191786}{191837}He abierto los ojos.
{192285}{192335}¿Qué es ese olor?
{192805}{192877}- ¿Adónde están todos?|- Oh, no. ¿Qué sucede?
{192892}{192930}¡Sr. Durden!
{192956}{193002}¡Oh, mi Dios!
{193129}{193206}¿Está bien... señor?
{193208}{193304}- Sí. Estoy bien.|- Se le ve mal. ¿Qué sucedió?
{193304}{193400}- Nada, no es problema.|- No, no, no, señor. En serio.
{193402}{193470}- Qué aspecto atroz. Ayúdenlo.|- Estoy bien.
{193472}{193558}Mire, estoy bien... Todo está bien.
{193637}{193666}¡Déjeme!
{193671}{193745}- Déjela.|- ¡Cristo!
{193748}{193791}¡Tú!
{193791}{193841}Hola, Marla.
{193853}{193968}- Déjenla conmigo. Los encuentro abajo.|- ¿Está seguro?
{193971}{194021}Sí, estoy seguro.
{194047}{194146}¡Hijo de puta!|¿Qué es este juego demencial?
{194148}{194213}Mandarme al campo...|¡Mi Dios, tu cara!
{194215}{194251}Sí, ya sé.
{194366}{194412}¿Qué pasó?
{194414}{194465}- No preguntes.|- Te dispararon.
{194467}{194517}- Sí, fue un disparo.|- Oh, mi Dios.
{194539}{194611}- No puedo creer que esté en pie.|- Es uno de los duros.
{194702}{194747}¿Quién fue?
{194750}{194810}Yo mismo.
{194812}{194860}Traigan gasas.
{194894}{194942}¿Te disparaste tú mismo?
{194944}{195009}Sí, pero estoy bien. Marla, mírame.
{195009}{195064}Estoy bien.
{195066}{195162}Confía en mí. Todo acabará bien.
{195469}{195563}Fue un período extraño de mi vida.
