name: "mdb"

services:
  web:
    build:
      context: ./web
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./web/public:/app/public

  db:
    image: redis/redis-stack:latest
    volumes:
      - ./redis:/data
      - ./redis/redis.conf:/redis-stack.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  downloads:
    build:
      context: ./downloads
      args:
        - TRANSMISSION_USER = ${TRANSMISSION_USER}
        - TRANSMISSION_PASS = ${TRANSMISSION_PASS}
        - TMDB_API_KEY = ${TMDB_API_KEY}
        - OPENSUBTITLES_KEY = ${OPENSUBTITLES_KEY}
        - OPENSUBTITLES_USER = ${OPENSUBTITLES_USER}
        - OPENSUBTITLES_PASS = ${OPENSUBTITLES_PASS}
    volumes:
      - ./downloads/web/src:/app/web/src
      - ./downloads/web/nodemon.json:/app/web/nodemon.json
      - ./downloads/web/tsconfig.json:/app/web/tsconfig.json
      - ./downloads/scripts:/app/scripts
      - ./web/public/Movies/Downloads:/downloads
      - ./downloads/transmission/transmission-daemon:/app/transmission
    ports:
      - 8080:8080
      - 9091:9091
    env_file:
      - .env